### ISSUE TITLE
FCntUp updated incorrectly

### ISSUE THREAD

**Issue by ivajloip** [brocaar/loraserver#1]
According to [this][1] specification (and I believe it is the latest), when you receive an uplink message, you update your FCntUp to match the FCnt, if its value seems correct. The server might have missed some messages, but if they are *unconfirmed*, that could be OK (if they are not too many).

> At the receiver side, the corresponding counter is kept in sync with the value received provided the
> value received has incremented compared to the current counter value and is less than the value 
> specified by MAX_FCNT_GAP 1 after considering counter rollovers.

In the code [here][2], the counter FCntUp is directly incremented. Due to this, at a later time the following problems can occur:

* Difference between observed and actual traffic getting bigger than MAX_FCNT_GAP and thus discarding possibly valid messages.
* Fail to detect resending of a *confirmed* message. For example, if the device sends an unconfirmed message which is lost and a confirmed message which is received, but it's confirmation is lost, it will resend the packet. Due to the incorrect FCntUp, it will be impossible to detect that the message is already handled, but the confirmation was lost.

I am working on a pull request with a fix.

[1]: https://www.lora-alliance.org/portals/0/specs/LoRaWAN%20Specification%201R0.pdf
[2]: https://github.com/brocaar/loraserver/blob/master/loraserver.go#L131

**Comment by brocaar** [comment]
Good catch :+1: It should have been the frame counter of the packet + 1 (which is at an early stage already validated and expanded to the full 32 bit counter). I will look into it later today or tomorrow.
