### ISSUE TITLE
Continuation of #95 - Add more network info like Channel/Suband and SF

### ISSUE THREAD

**Issue by TimelessNL** [brocaar/loraserver#102]
As a continuation of #95 I would like to add more networking information like the RX channel/SubBand and received Spreading Factor.

Would that be possible?

**Comment by brocaar** [comment]
Yes, I'll add that soon. I think with ADR in the pipeline, it would also be nice to see the effect of the adaptive data-rate engine at the application-side.

**Comment by TimelessNL** [comment]
That's great, thanks :)

**Comment by brocaar** [comment]
This has been implemented and released as LoRa App Server 0.2.0. See https://docs.loraserver.io/lora-app-server/mqtt-topics/#receiving for an example.
