### ISSUE TITLE
Class C

### ISSUE THREAD

**Issue by pejril** [brocaar/loraserver#107]
Hello Mr. Brocaar ! You Lora server is a great project  :-) I would like to ask you about support of Class C.... Have you this support in you future plans ? Class C support will be the next great advantage of your server. Thanx for your answer.

**Comment by brocaar** [comment]
I don't have an ETA, but this is definitely a feature that will be added to LoRa Server.

**Comment by kuripiiritus** [comment]
Hei, is there any news with the class C support?

**Comment by brocaar** [comment]
Not yet, but the good news is that from Feb on, I'll be able to dedicate more time to this project :-)

**Comment by brocaar** [comment]
This has already been implemented. Forgot to close the issue.
