### ISSUE TITLE
Error in Compiling

### ISSUE THREAD

**Issue by Umair-Anwar** [brocaar/loraserver#125]
I have followed the instructions to compile with docker compose.
but i always get an error 'start_linux_init.go (178) exec format error'

I'm using raspbian on raspberry pi 3 (armv7)

**Comment by brocaar** [comment]
I have no experience with Docker on ARM, but it looks like the container that you're using is either not for ARM or you're not compiling for the ARM architecture.

**Comment by ivajloip** [comment]
Speaking of Docker + ARM + Golang - [this][1] comes to mind :)

[1]: https://hub.docker.com/r/acklio/golang-armhf/

**Comment by ivajloip** [comment]
I had missed that issue. If you still need some inspiration, you can check out [this][1] Dockerfile that generates mosquitto for ARMv7 :) The result can be found [here][2].

[1]: https://bitbucket.org/acklio/docker-mosquitto/src/9cbbb2319c3b1a3cbeb788910b6e6b870d636552/armhf/Dockerfile?at=master&fileviewer=file-view-default
[2]: https://hub.docker.com/r/acklio/mosquitto/tags/
