### ISSUE TITLE
How to create Users in LoRa App server

### ISSUE THREAD

**Issue by kamran000** [brocaar/loraserver#128]
I have installed LoRa server and LoRa App server , accessed App server through http , but there is only option of adding devices , how can i create users in it?

**Comment by brocaar** [comment]
This is currently not yet implemented, but is definitely something I'll be working on soon. Could you please create a feature request at https://github.com/brocaar/lora-app-server so you can track the progress (as this feature should be part of LoRa App Server, not LoRa Server)?

**Comment by kamran000** [comment]
yeah sure. Thanks it will be very helpful

**Comment by kamran000** [comment]
How to create feature request?

**Comment by brocaar** [comment]
I meant, could you create an issue describing the feature request for the above repo :-)

**Comment by kamran000** [comment]
ok :-)
