### ISSUE TITLE
Install loraserver on windows

### ISSUE THREAD

**Issue by ShahabR** [brocaar/loraserver#131]
Hi,
Is there any help for installing lora server on windows os? In linux it talks about configuring lora server after installation, how about on windows? Thanks

**Comment by hecko** [comment]
One way would be to use Docker.

Dňa 13.2.2017 1:20 PM používateľ "ShahabR" <notifications@github.com>
napísal:

**Comment by brocaar** [comment]
Note that you can pass all the configuration as arguments. I don't have any experiences with setting up windows services, but if you run `loraserver.exe --help` on the command-line, you'll see all available arguments :-)

**Comment by ShahabR** [comment]
Can you explain more about using docker in this case @hecko ( I know a little about docker) ? Thanks.
I've developed several windows service in .net language but I'm not familiar with this type of deployment( I use to install service with a batch file and... ) , anyway I will try using --help argument as you said, thanks brocaar.
