### ISSUE TITLE
LoRa Join request is being rejected

### ISSUE THREAD

**Issue by Howlinmoon** [brocaar/loraserver#132]
Hi,
I have the Docker install up and running, and have performed very minimal configuration via the gui.
I already had my Gateway and Node setup for The Things Network - so I just modified my gateway to point to my Docker install, and added a node via the gui that reflected my current node Id, App Id and App Key I was using with TTN.

Attached should be two log files:

An excerpt taken from the syslog on the Docker installation
A corresponding excerpt taken from tcpdump running on the gateway device
10.16.74.58 = server
10.16.74.124 = gateway

The initial join seems to fail due to the data rates (which I have been assured are legal by our developers - and work fine on the TNN server)

After the initial join failure, there is a pileup of failures due to the client re-using the DevNonce.
At first, I thought I was seeing this issue:
https://github.com/brocaar/loraserver/issues/116

But I'm pretty sure it's just a side effect of the initial Join being rejected.

Again, I did very minimal configuration of my node entry - everything after the Application Key is left at its default value.
[syslog.txt](https://github.com/brocaar/loraserver/files/777683/syslog.txt)
[tcpdump.txt](https://github.com/brocaar/loraserver/files/777684/tcpdump.txt)

**Comment by brocaar** [comment]
> The initial join seems to fail due to the data rates (which I have been assured are legal by our developers - and work fine on the TNN server)

Are you sure you've configured the correct `BAND` configuration for LoRa Server?
