### ISSUE TITLE
Support link check validation?

### ISSUE THREAD

**Issue by sabas1080** [brocaar/loraserver#137]
Hi @brocaar 

I am using the lmic library for Arduino and a section mention

> Disable link check validation (automatically enabled
> during join, but not supported by TTN at this time).

https://github.com/matthijskooijman/arduino-lmic/blob/master/examples/ttn-otaa/ttn-otaa.ino#L93

Do you support link check validation? And so we can eliminate this line

Thanks

**Comment by brocaar** [comment]
Not yet, but there is already an issue to track this feature: https://github.com/brocaar/loraserver/issues/111
