### ISSUE TITLE
collectAndCallOnce func modify~

### ISSUE THREAD

**Issue by yzk0281** [brocaar/loraserver#138]
Hi, broccar
your collectAndCallOnce function is for dealing multi-gateway processing the same packet, it use a key and a lock to realise that.
However, your key is like this:
key := "collect_" + hex.EncodeToString(rxPacket.PHYPayload.MIC[:])

If there is a lot of nodes, this key might be the same for different nodes, so I turned the key into this:
key := "collect_" + hex.EncodeToString(rxPacket.PHYPayload.MIC[:]) + "_" + hex.EncodeToString(macPL.FHDR.DevAddr[:])

How do you think about it?

**Comment by brocaar** [comment]
Yes, that is correct. Note that it is not guaranteed that there is a `DevAddr` available (e.g. in case of a join-request).
