### ISSUE TITLE
log lib change

### ISSUE THREAD

**Issue by yzk0281** [brocaar/loraserver#140]
Hi, Brocaar
Any plan to change log lib to glog?
logrus don't support log rotation, it's ugly.

**Comment by brocaar** [comment]
Currently I don't have any plans to change to an other log library, as I'm quite happy with logrus. Why is it ugly?

Personally I don't think it is the responsibility of the log library to "manage" your logs. I think this is more a responsibility of the service above the service outputting logs (e.g. systemd, supervisor, init.d). For linux I would recommend you to take a look at: http://www.linuxcommand.org/man_pages/logrotate8.html. 

When using the `.deb` packages, this is already setup for you: https://github.com/brocaar/loraserver/blob/master/packaging/deb/logrotate.
