### ISSUE TITLE
Documentation mistype for Class C 

### ISSUE THREAD

**Issue by glederer007** [brocaar/loraserver#142]
The documentation on https://docs.loraserver.io/loraserver/features/ states:

> Class C
LoRa Server has full support for Class-C devices. It will remember the last rx parameters (of each gateway that received the uplink), so that the nearest gateway can be used for the Class-C uplink. An uplink can be scheduled by using the NetworkServer.PushDataDown API method.

Shouldn't it be "... Class-C downlink. A downlink can be..."?

**Comment by brocaar** [comment]
Good catch! I'll fix it.
