### ISSUE TITLE
Tools for test

### ISSUE THREAD

**Issue by panyingyun** [brocaar/loraserver#144]
brocaar, here is some tools that I develop them for test. Maybe useful for other friends.

1. https://github.com/panyingyun/watch   
        Watch message received from loraserver/gateway/application by LoRaWAN™

2. https://github.com/panyingyun/vmloragateway
         Visual Machine(Lora Gateway) connect to lora-gateway-bridge for test LoRaWAN™ server benchmark or others(NS+NC+AS)

3. https://github.com/panyingyun/vmloranode (plan to do)
   Vmloranode create Virtual node for test LoRaWAN™ gateway and LoRaWAN™ network(NS + AS+ NC)

**Comment by brocaar** [comment]
Thanks for sharing! I'll add a third-party tools documentation page :-) I'll close the issue once these links are added.

**Comment by brocaar** [comment]
Added in https://github.com/brocaar/docs.loraserver.io/commit/90cd47df94423cb9997b3bdebc777aa7dda0b71a.
