### ISSUE TITLE
Some question about Class C multicast downlink frames

### ISSUE THREAD

**Issue by panyingyun** [brocaar/loraserver#145]
Class C multicast downlink frames
========
some use case that may need to use class multicast messages. So maybe has some issues:

Within  LoRaWan Spec,  some words "The multicast address and associated network session key and application session key  must come from the application layer. The same limitations apply for Class C multicat downlink frames.  They are not allowed to carry MAC commands ....."
 
Q1: who generate multicast address. In LoRaWAN Spec "must come from the application layer" what's it mean, AS or NS to manager these parameters?

Q2: who manager multicat address and multicast key ?

Q3: how to divide group of many nodes dynamicly, because a node maybe change group( from old group to new group) ?
       
Here is some only my own idea ( Is it right ? ):

A multicast address is somewhat outside the standardized LoRaWAN protocol. 
When we look at the reference LoraMAC implementation on Github (https://github.com/Lora-net/LoRaMac-node/blob/master/src/mac/LoRaMac.c ) 

We get a struct
``` shell
typedef struct sMulticastParams
{
    /*!
     * Address
     */
    uint32_t Address;
    /*!
     * Network session key
     */
    uint8_t NwkSKey[16];
    /*!
     * Application session key
     */
    uint8_t AppSKey[16];
    /*!
     * Downlink counter
     */
    uint32_t DownLinkCounter;
    /*!
  * Reference pointer to the next multicast channel parameters in the list
     */
    struct sMulticastParams *Next;
}MulticastParams_t;
```
```
All these multicast device parameters (multicast address, multicast network/application session keys)
must either come via ABP or sent with an user defined command over the application layer from the NS to the device.
A device checks always after receiving a frame if the unicast address matches the incoming downlink frame. 
If it does not match, then the device checks next if the incoming frame address matches a configured multicast address.  
If multicast is detected, then the device checks the MIC and the Downlink-Counter. If all these checks were successful, 
then the frame is decrypted with the multicast AppSKey and processed on the application layer.  
So multicast only works in the downlink direction from NS->device and it is only possible to use 
UnconfirmedDataDown messages (no acknowledges). 
```

**Comment by brocaar** [comment]
This is a bit a grey area for me too. How I understand the "application layer" is that this means that this is not covered by the LoRaWAN protocol:

So for example in the future you could potentially create a multicast group of nodes, and LoRa App Server will generate this information for you. Or you generate it yourself and enter this information in LoRa App Server. Or maybe the multicast feature would be on an per application level? So that you create a multicast application?

Then how you provision your node with these keys is up to your "application layer" / your own firmware.
