### ISSUE TITLE
Question: Receive/send data over REST API

### ISSUE THREAD

**Issue by crdn** [brocaar/loraserver#148]
Hi brocaar

Thank you very much for sharing your great solution!

I set up your project and it runs without problems. Now I would like to visualize the received sensor data on a website. The easiest way would be to receive and send data over the REST API, because it is plattform independent.

Is there any possibility to get the data over the REST API and if not, what would be the best way? Is it planned to extend the REST API as suggested or not?

Thank you very much!
crdn

**Comment by brocaar** [comment]
Thanks! Currently not, but it might be a future feature of LoRa App Server to support HTTP callbacks next to MQTT. Could you re-open this issue at https://github.com/brocaar/lora-app-server?
