### ISSUE TITLE
Error pq: relation "gateway" does not exist (code: 2)

### ISSUE THREAD

**Issue by rabih9780** [brocaar/loraserver#153]
![img_9522](https://cloud.githubusercontent.com/assets/20864891/24465190/0cf4600e-1461-11e7-8d74-a806a09f2176.JPG)

I updated all the LORA software but i am getting the error above when i access lora-app-server website. Any idea on how to fix this error?

Thanks for all your hard work btw :)

**Comment by brocaar** [comment]
Yes, you need to start LoRa Server with this flag:

```
--db-automigrate                        automatically apply database migrations [$DB_AUTOMIGRATE]
```
