### ISSUE TITLE
Network Quality Question

### ISSUE THREAD

**Issue by Chill0309** [brocaar/loraserver#161]
Hi, should running a gateway as a packet forwarder and having the network server in the cloud run ok if the gateway is only connected with a 3G/GPRS SIM connection rather than a 'good', wired internet connection? Thanks.

**Comment by brocaar** [comment]
The think you need to take care about is the roundtrip time of packets between the "cloud" and your gateway. For OTAA you have max 5 second, for downlink data by default 1 second. Note the latter one is configurable (Receive window delay).

Could you close this issue when it answers your question?

**Comment by Chill0309** [comment]
Thanks, I think this fits ok with the type of pings we're getting. Do you have any gauge for how capable it is dealing with heavy loads on the lora side, i presume its all quite lightweight and scales fairly well?

**Comment by brocaar** [comment]
Lets move this topic to https://forum.loraserver.io/ in case you have any further questions :-)
