### ISSUE TITLE
Where is payload.

### ISSUE THREAD

**Issue by Osman9** [brocaar/loraserver#164]
Hello everyone,

This is my very first post and i just started to use brocaar lora server. I am using microchip evaluation lora kit EU version. I have my lora server up. I have created an application in dashboard and registered a node. The node is sending the data but that data is no where to be seen. I am attaching the screen shots 
![gateway data](https://cloud.githubusercontent.com/assets/28051246/25433664/75e9d77c-2a89-11e7-93a7-c9896b806b96.png)
![lora_app_server_data](https://cloud.githubusercontent.com/assets/28051246/25433665/75ea49fa-2a89-11e7-943d-fc5c68e61707.png)
![loraserver_data](https://cloud.githubusercontent.com/assets/28051246/25433663/75e9c386-2a89-11e7-892c-5ebf024d09cc.png)

**Comment by brocaar** [comment]
All data is published over MQTT. Please refer to https://docs.loraserver.io/lora-app-server/mqtt-topics/.
