### ISSUE TITLE
Missing packets or frames ??

### ISSUE THREAD

**Issue by kazi93** [brocaar/loraserver#165]
Any suggestions or advice to visualise the packets or frames send by the Node?  thanks 

pi@Loraserver:~ $ sudo systemctl status loraserver
● loraserver.service - LoRa Server
   Loaded: loaded (/lib/systemd/system/loraserver.service; enabled)
   Active: active (running) since Fri 2017-04-28 12:52:15 UTC; 5h 7min ago
     Docs: https://docs.loraserver.io
 Main PID: 18541 (loraserver)
   CGroup: /system.slice/loraserver.service
           └─18541 /usr/bin/loraserver
                                                                    
Apr 28 12:52:16 Loraserver loraserver[18541]: time="2017-04-28T12:52:16Z" level=info msg="backend/gateway: connected t...erver"
Apr 28 12:52:16 Loraserver loraserver[18541]: time="2017-04-28T12:52:16Z" level=info msg="backend/gateway: subscribing.../+/rx"
Apr 28 12:52:16 Loraserver loraserver[18541]: time="2017-04-28T12:52:16Z" level=info msg="migrated node-sessions to ne...ated=0
Apr 28 12:52:16 Loraserver loraserver[18541]: time="2017-04-28T12:52:16Z" level=info msg="applying database migrations"
Apr 28 12:52:16 Loraserver loraserver[18541]: time="2017-04-28T12:52:16Z" level=info msg="backend/gateway: subscribing...stats"
Apr 28 12:52:16 Loraserver loraserver[18541]: time="2017-04-28T12:52:16Z" level=info msg="migrations applied" count=0
Apr 28 12:52:16 Loraserver loraserver[18541]: time="2017-04-28T12:52:16Z" level=info msg="starting api server" bind="0...s-key=
Apr 28 17:06:07 Loraserver loraserver[18541]: time="2017-04-28T17:06:07Z" level=info msg="gateway created" mac=b827ebffff5e0aae
Apr 28 17:12:54 Loraserver loraserver[18541]: time="2017-04-28T17:12:54Z" level=info msg="gateway updated" mac=b827ebffff5e0aae
Apr 28 17:36:49 Loraserver loraserver[18541]: time="2017-04-28T17:36:49Z" level=info msg="node-session saved" dev_addr...123456

pi@Loraserver:~ $ sudo systemctl status lora-app-server
● lora-app-server.service - LoRa App Server
   Loaded: loaded (/lib/systemd/system/lora-app-server.service; enabled)
   Active: active (running) since Fri 2017-04-28 12:51:35 UTC; 5h 9min ago
     Docs: https://docs.loraserver.io
 Main PID: 18498 (lora-app-server)
   CGroup: /system.slice/lora-app-server.service
           └─18498 /usr/bin/lora-app-server

Apr 28 17:16:54 Loraserver lora-app-server[18498]: time="2017-04-28T17:16:54Z" level=info msg="node updated" applicatio...23456
Apr 28 17:29:37 Loraserver lora-app-server[18498]: time="2017-04-28T17:29:37Z" level=info msg="node updated" dev_eui=12...23456
Apr 28 17:29:37 Loraserver lora-app-server[18498]: time="2017-04-28T17:29:37Z" level=info msg="node updated" applicatio...23456
Apr 28 17:30:01 Loraserver lora-app-server[18498]: time="2017-04-28T17:30:01Z" level=info msg="application updated" id=...ensor
Apr 28 17:35:02 Loraserver lora-app-server[18498]: time="2017-04-28T17:35:02Z" level=info msg="node updated" dev_eui=12...23456
Apr 28 17:35:02 Loraserver lora-app-server[18498]: time="2017-04-28T17:35:02Z" level=info msg="node updated" applicatio...23456
Apr 28 17:36:49 Loraserver lora-app-server[18498]: time="2017-04-28T17:36:49Z" level=info msg="node updated" dev_eui=12...23456
Apr 28 17:36:49 Loraserver lora-app-server[18498]: time="2017-04-28T17:36:49Z" level=info msg="node activated" applicat...23456
Apr 28 17:37:53 Loraserver lora-app-server[18498]: time="2017-04-28T17:37:53Z" level=info msg="node updated" dev_eui=12...23456
Apr 28 17:37:53 Loraserver lora-app-server[18498]: time="2017-04-28T17:37:53Z" level=info msg="node updated" applicatio...23456
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by dietb** [comment]
You can see some of the data in the mqtt topic, but it depends on what data you're looking for specifically.

$ mosquitto_sub (args) -t "application/#"
