### ISSUE TITLE
Microchip Lora Gateway

### ISSUE THREAD

**Issue by sicsim** [brocaar/loraserver#167]
Hi
 Has anyone managed to implement  this server with the Michip Lora gateway? 
I managed to install as stated but I cannot connect to the severs with this unit

**Comment by brocaar** [comment]
Yes, I have a Microchip gateway which I used for testing. All works fine, except the stats (which is a known Microchip bug). Make sure you setup the correct hostname and portnumbers, the default might not be 1700 (which is used by LoRa Gateway Bridge). I'll close this issue, lets continue on finding the issue in https://gitter.im/loraserver/lora-gateway-bridge.
