### ISSUE TITLE
How to broadcast a packet from gateway?

### ISSUE THREAD

**Issue by Yaoshicn** [brocaar/loraserver#172]
Hi, brocaar,

Thank you for your work.

I am wondering if it is possible to broadcast a packet using your tool chain. I only found how to send a downlink to a specific node. Thank you.

Best Regards,
Xuanliang

**Comment by brocaar** [comment]
Please see https://docs.loraserver.io/lora-gateway-bridge/topics/ in case you would like to interact with the gateway directly.

**Comment by Yaoshicn** [comment]
Thank you for your help!
