### ISSUE TITLE
Manually setting Spread Factor on up and down -link

### ISSUE THREAD

**Issue by carlberg74** [brocaar/loraserver#173]
Hi,
Is it possible to manually set the spread factory to something else then 12?
I have a device that might work better using SF9 and I would like to test this.

Cheers
-Anders

**Comment by brocaar** [comment]
I think your question duplicates #160 (which would allow you to issue mac-commands to control for example the SF). Let's continue the discussion there.

Of course you could also set this on the node itself too as most firmwares have a way to change these parameters (like the DevEUI, AppEUI, AppKey etc...)
