### ISSUE TITLE
Fault Persistence 

### ISSUE THREAD

**Issue by siscia** [brocaar/loraserver#176]
I would like to start a conversation around fault persistance.

We are considering to use the whole infrastructure in a quite complex architecture.

In this context I need to be sure that the software is resilience to any fault that may happen.

We successfully ran the a beta of the lora infrastructure => {loraserver + lora-app-server + lora-gateway-bridge + vernemq + redis + postgres} on a single machine and we are very happy with the results so far.

In the process of scaling we will spread the deploy of the components in different machine. Thus one of the most common problem I am expecting will be network partition.

What happens if suddenly Redis is not reachable any more? What about Postgres? What if the lora-app-server and the loraserver canno't communicate anymore? What is the MQTT server / cluster goes down? 

Clearly I am starting my own investigation about these points but I simply wanted to get the conversation going and collect feedback.

@brocaar if you don't believe the issues is appropriate (it add too much noise, it is too broad, it is not useful for your workflow, whatever) feel free to close it. :)

**Comment by brocaar** [comment]
I'm closing this issue. In case you would open this discussion again, please create a topic at https://forum.loraserver.io :-)
