### ISSUE TITLE
In Relax frame-counter mode downlink fcnt get reset after sometime

### ISSUE THREAD

**Issue by vikasrohal** [brocaar/loraserver#181]
Due to changes in loraserver 0.17.1 of issue #133 , Downlink frame counter reset to 0 even end device is not reset.Due to downlink fcnt 0, MIC got failed at end device and re-transmission of same packet get started.Please see the log of same 

73 40 61 72 74 69 6E 67 20 77 69 74 68 20 64 65 66 61 75 6C 74 20 73 65 74 74 69 6E 67 73 0A聽
**uplink frame**-80 11 11 11 11 00 00 00 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 2F 91 B0 95 31 31 31 31
**downlink frame**60 11 11 11 11 20 **00 00** 75 70 A8 22 41 43 4B
80 11 11 11 11 00 01 00 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 73 3A 04 BE 31 31 31 31
60 11 11 11 11 20 **01 00** 50 1A 6E 67 41 43 4B
80 11 11 11 11 00 02 00 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 EE F7 76 47 31 31 31 31
60 11 11 11 11 20 **02 00** 9B 06 D7 76 41 43 4B
80 11 11 11 11 00 03 00 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 24 62 C8 C5 31 31 31 31
60 11 11 11 11 20 **03 00** DF 32 0D 16 41 43 4B
80 11 11 11 11 00 04 00 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 3E 1A 9C 4E 31 31 31 31
60 11 11 11 11 20 **04 00** E1 02 39 48 41 43 4B
80 11 11 11 11 00 05 00 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 B9 3E E6 FD 31 31 31 31
60 11 11 11 11 20 **05 00** 8B 7A 68 9C 41 43 4B
80 11 11 11 11 00 06 00 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 07 A0 04 8C 31 31 31 31
60 11 11 11 11 20 **06 00** 76 AB D5 63 41 43 4B
80 11 11 11 11 00 07 00 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 0A 6D 89 99 31 31 31 31
60 11 11 11 11 20 **07 00** 26 90 37 71 41 43 4B
80 11 11 11 11 00 08 00 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 42 1E B7 90 31 31 31 31
60 11 11 11 11 20 **08 00** FA CC 41 58 41 43 4B
80 11 11 11 11 00 09 00 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 4A E5 D7 9D 31 31 31 31
60 11 11 11 11 20 **09 00** 5F F9 5A 14 41 43 4B
80 11 11 11 11 00 0A 00 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 65 F2 1D A7 31 31 31 31
60 11 11 11 11 20 **0A 00** 0C 82 5D 73 41 43 4B
80 11 11 11 11 00 0B 00 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 7E 9F 37 E1 31 31 31 31
60 11 11 11 11 20 **0B 00** 6F B0 C6 57 41 43 4B
80 11 11 11 11 00 0C 00 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 02 3C 6E 55 31 31 31 31
60 11 11 11 11 20 **0C 00** 19 67 69 8E 41 43 4B
80 11 11 11 11 00 0D 00 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 C9 F2 C3 71 31 31 31 31
60 11 11 11 11 20 **00 00** 75 70 A8 22-**fcnt reset to 0 of downlink frame**
60 11 11 11 11 20 **00 00** 75 70 A8 22- **Retry**
60 11 11 11 11 20 **00 00** 75 70 A8 22
60 11 11 11 11 20 **00 00** 75 70 A8 22
60 11 11 11 11 20 00 00 75 70 A8 22
60 11 11 11 11 20 00 00 75 70 A8 22
80 11 11 11 11 00 0E 00 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 31 A1 A7 14 83 31 31 31 31
60 11 11 11 11 20 01 00 50 1A 6E 67
60 11 11 11 11 20 00 00 75 70 A8 22
60 11 11 11 11 20 00 00 75 70 A8 22

**Comment by brocaar** [comment]
This was fixed in [0.17.2](https://github.com/brocaar/loraserver/releases/tag/0.17.2) 😉
