### ISSUE TITLE
main.go:31:2: cannot find package "github.com/brocaar/loraserver/internal/migrations"

### ISSUE THREAD

**Issue by xiaoyuvax** [brocaar/loraserver#191]
main.go:31:2: cannot find package "github.com/brocaar/loraserver/internal/migrations" in any of:
        \gopath\src\github.com\brocaar\loraserver\vendor\github.com\brocaar\loraserver\internal\migrations (vendor tree)        
        \gopath\src\github.com\brocaar\loraserver\internal\migrations (from $GOPATH)
...

there's only a folder named 'migration' ,but no such a folder named 'migrations'.

**Comment by brocaar** [comment]
What command did you use for compiling? What Go version did you use etc...?

**Comment by xiaoyuvax** [comment]
go version = go1.8.3 windows/amd64

\GoPath\src\github.com\brocaar\loraserver\cmd\loraserver>go build
main.go:31:2: cannot find package "github.com/brocaar/loraserver/internal/migrations" in any of:
        \gopath\src\github.com\brocaar\loraserver\vendor\github.com\brocaar\loraserver\internal\migrations (vendor tree)
        \Go\src\github.com\brocaar\loraserver\internal\migrations (from $GOROOT)
        \gopath\src\github.com\brocaar\loraserver\internal\migrations (from $GOPATH)

**Comment by brocaar** [comment]
Please see the `Makefile` :-) `make build` should work.

**Comment by xiaoyuvax** [comment]
The Makefile was stuck on compiling of the go-binddata package due to that golang's moved the golang.org/x/tools/cmd/vet to another path in go sources. don't know how to work it around. :(

**Comment by brocaar** [comment]
Do you mean you couldn't install `go-binddata`? Could you post your exact error that you get when running `make`?

**Comment by xiaoyuvax** [comment]
d:\GoPath\src\github.com\jteeuwen\go-bindata>make
make -C testdata
make[1]: Entering directory `/d/GoPath/src/github.com/jteeuwen/go-bindata/testdata'
go get github.com/kisielk/errcheck
go get golang.org/x/tools/cmd/vet
package golang.org/x/tools/cmd/vet: unrecognized import path "golang.org/x/tools/cmd/vet" (https fetch: Get https://golang.org/x/tools/cmd/vet?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
make[1]: *** [vet] Error 1
make[1]: Leaving directory `/d/GoPath/src/github.com/jteeuwen/go-bindata/testdata'
make: *** [all] Error 2

**Comment by brocaar** [comment]
Not sure why you would run `make` in the `go-bindata` package. You could easily install `go-bindata` by executing: `go get github.com/jteeuwen/go-bindata/...`

**Comment by xiaoyuvax** [comment]
oh sorry ,i forgot to paste the intermediate step:when building LoraWan Server,it cascadingly build and install go-bindata and fails,saying cannot find go-bindata executable and the MAKE breaks. So i go to go-binddata path and manually build it in order to get the package installed,but it stuck at the cmd/vet import.

**Comment by xiaoyuvax** [comment]
D:\GoPath\src\github.com\brocaar\loraserver>make
Generating static files
cmd\loraserver\main.go:1: running "go-bindata": exec: "go-bindata": executable file not found in %PATH%
make: *** [statics] Error 1

**Comment by brocaar** [comment]
As I mentioned before, you need to execute `go get github.com/jteeuwen/go-bindata/...` to install this. See also https://docs.loraserver.io/loraserver/community/source/ for more instructions.

**Comment by xiaoyuvax** [comment]
Solved! Do not use go-bindata‘s makefile,but just install the main program or download an executable somewhere.
finally,loraserver installed successfully!
Thanks anyway.
