### ISSUE TITLE
HTTP error

### ISSUE THREAD

**Issue by alexandruradovici** [brocaar/loraserver#199]
Hello,

I am trying to run loraserver on an Ubuntu (Linux ubuntu 4.10.0-19-generic #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux). I am getting the following error in the logs whenever I am trying to access the web interface.

```
Jul 04 12:27:25 ubuntu loraserver[10799]: time="2017-07-04T12:27:25+03:00" level=info msg="transport: http2Server.HandleStreams received bogus greeting from client: "GET / HTTP/1.1\r\nUser-Age""
```

Any ideas?

**Comment by brocaar** [comment]
Please open an issue in https://github.com/brocaar/lora-app-server when you have an issue with the web-interface. However, I think you forgot to put `https://` in from of the URL (note the **s**).
