### ISSUE TITLE
two questions: no journal file were found ;   can not start lora-app-service

### ISSUE THREAD

**Issue by llb126yx** [brocaar/loraserver#212]
Hi brocaar, very thanks for you. i build this lora server on my raspberyy pi 3. i have installed all the software.  but when i excute "journalctl -u loraserver", it mentioned "no journal files were found" . I just skip this. then I start lora-app-server , it just failed. 
flowing is the infomation:
sudo systemctl start lora-app-server
pi@raspberrypi:~ $ sudo systemctl status lora-app-server
● lora-app-server.service - LoRa App Server
   Loaded: loaded (/lib/systemd/system/lora-app-server.service; enabled)
   Active: failed (Result: start-limit) since Wed 2017-07-26 03:03:02 UTC; 6s ago
     Docs: https://docs.loraserver.io
  Process: 2598 ExecStart=/usr/bin/lora-app-server (code=exited, status=1/FAILURE)
 Main PID: 2598 (code=exited, status=1/FAILURE)
Jul 26 03:03:02 raspberrypi systemd[1]: Unit lora-app-server.service entered failed state.
Jul 26 03:03:02 raspberrypi systemd[1]: lora-app-server.service holdoff time over, scheduling restart.
Jul 26 03:03:02 raspberrypi systemd[1]: Stopping LoRa App Server...
Jul 26 03:03:02 raspberrypi systemd[1]: Starting LoRa App Server...
Jul 26 03:03:02 raspberrypi systemd[1]: lora-app-server.service start request repeated too quickly, refusing to start.
Jul 26 03:03:02 raspberrypi systemd[1]: Failed to start LoRa App Server.
Jul 26 03:03:02 raspberrypi systemd[1]: Unit lora-app-server.service entered failed state.

i did not see any information about this question ,hope you can reply, thanks

**Comment by brocaar** [comment]
Could you please post your questions in https://forum.loraserver.io? I'm trying to move support questions to the forum and keep questions related to code / bugs on GitHub (e.g. my backlog of work to do). Please create two topics, that way they can be used by future users with the same questions :-)
