### ISSUE TITLE
loraserver problem (Failed to start LoRa Server.)

### ISSUE THREAD

**Issue by renapei** [brocaar/loraserver#217]
Hello brocaar, congratulations for the guide to build a network server..

 I have a problem, I buildit over the network server all (bridge / server / app) and it was working properly for about a month.
Now, it's from yesterday that it no longer accepts my final nodes, checking the settings is all right (bridge / server / app-server file conf) but if I try to restart server I just get: Failed to start LoRa Server ...
I've already tried the solutions you've proposed to other users,how this:

# stop the lora-app-server process
systemctl stop lora-app-server
# load configuration
set -a
source /etc/default/lora-app-server
# start loraserver manually
lora-app-server

but they did not work with me..
I checked the two DBs, jwt secret broker etc, but it's all done, I do not know how to fix it.
I have two gateways (kerlink) attached to the network ..
Some advice on how to follow up?
I attach the serverlora's log

when try to start loraserver
"
Aug 03 15:50:44 GatewayBridge systemd[1]: loraserver.service: Main process exited, code=exited, status=1/FAILURE
Aug 03 15:50:44 GatewayBridge systemd[1]: loraserver.service: Unit entered failed state.
Aug 03 15:50:44 GatewayBridge systemd[1]: loraserver.service: Failed with result 'exit-code'.
Aug 03 15:50:44 GatewayBridge systemd[1]: loraserver.service: Service hold-off time over, scheduling restart.
Aug 03 15:50:44 GatewayBridge systemd[1]: Stopped LoRa Server.
Aug 03 15:50:44GatewayBridge systemd[1]: Started LoRa Server.
Aug 03 15:50:44 GatewayBridge loraserver[40804]: time="2017-08-03T15:50:44Z" level=info msg="starting LoRa Server" band="EU_863_870" docs="https://docs.loraserver.io/" net_id=010203 version=0.20.0

Aug 03 15:50:44 GatewayBridge loraserver[40804]: time="2017-08-03T15:50:44Z" level=info msg="migrated node-sessions to new format" errors=0 migrated=0
Aug 03 15:50:44 GatewayBridge loraserver[40804]: time="2017-08-03T15:50:44Z" level=info msg="applying database migrations"
Aug 03 15:50:44 GatewayBridge loraserver[40804]: time="2017-08-03T15:50:44Z" level=info msg="migrations applied" count=0
Aug 03 15:50:44 GatewayBridge loraserver[40804]: time="2017-08-03T15:50:44Z" level=info msg="starting api server" bind="0.0.0.0:8000" ca-cert= tls-cert= tls-key=
Aug 03 15:50:44 GatewayBridge systemd[1]: loraserver.service: Main process exited, code=exited, status=1/FAILURE
Aug 03 15:50:44 GatewayBridge systemd[1]: loraserver.service: Unit entered failed state.
Aug 03 15:50:44 GatewayBridge systemd[1]: loraserver.service: Failed with result 'exit-code'.
Aug 03 15:50:44 GatewayBridge systemd[1]: loraserver.service: Service hold-off time over, scheduling restart.
Aug 03 15:50:44 GatewayBridge systemd[1]: Stopped LoRa Server.
Aug 03 15:50:44 GatewayBridge systemd[1]: loraserver.service: Start request repeated too quickly.
Aug 03 15:50:44 GatewayBridge systemd[1]: Failed to start LoRa Server.
"
thanks

**Comment by brocaar** [comment]
I would like to refer you to the support forum located at https://forum.loraserver.io/, as this is probably related to your setup and not a bug. Please create a topic at the forum and we'll help you there :-)
