### ISSUE TITLE
packet types

### ISSUE THREAD

**Issue by akieni** [brocaar/loraserver#218]
Hi we like to establish mysql server connection to remote lora devices and we are curious if this packet forwarder can  be used for that scenario..
Thanks
chris

**Comment by brocaar** [comment]
Could you tell a bit more about your usecase? E.g. is your plan to log output from your node?

**Comment by akieni** [comment]
| Server 2 |------|Lora device |*********** radio link**************** |Lora Gateway |------| Mysql serve1|

This is what we want to achieve through a lora network .... Sending data back and forth between two or multiple location where there is a remote linux server with mysql... Of course this could be done through a 4G Lte , wimax or fiber but the deployment is in a rural area where we are doing forestry preservation....

**Comment by akieni** [comment]
| Server 2 |------|Lora device |*********** radio link**************** |Lora Gateway |------| Mysql serve1|

This is what we want to achieve through a lora network .... Sending data back and forth between two or multiple location where there is a remote linux server with mysql... Of course this could be done through a 4G Lte , wimax or fiber but the deployment is in a rural area where we are doing forestry preservation....

**Comment by brocaar** [comment]
I think this is out of scope of the LoRa Server project, but I don't see why you can't implement this yourself. E.g. put a custom application between the packet-forwarder and your MySQL db. Optionally, you could use https://github.com/brocaar/lora-gateway-bridge.

**Comment by akieni** [comment]
Unfortunately, I don't have the knowledge to build a custom application but I am ready to pay the required price if you can help me....  
Thanks very much for your reply..  :+1:

**Comment by siscia** [comment]
@akieni 

Feel free to send me a message, we may discuss your needs and see if it is possible to work together :)
