### ISSUE TITLE
Question: Band Configuration

### ISSUE THREAD

**Issue by RakshitAdmar** [brocaar/loraserver#219]
I want to configure the network server to work in the Indian Band. Which file do i make changes in ?
I can see in /etc/default/loraserver config file the extra frequencies option, but in my case i want to define the band corresponding to what is allowed in India.

**Comment by brocaar** [comment]
I'm planning to do a new release soon which includes the Indian band :-) These changes can already be found in https://github.com/brocaar/loraserver/tree/0_20_fixes.

**Comment by RakshitAdmar** [comment]
I have a very reliable system up and running and i don't want to put it down at the moment. Is there a fix for this? Is there some configuration file i can change ?

**Comment by brocaar** [comment]
The band configuration is defined in code (also since some logic is defined in functions), then in your LoRa Server configuration you define which band to use.
