### ISSUE TITLE
Bulk Register node

### ISSUE THREAD

**Issue by grendy** [brocaar/loraserver#220]
Hi, 
If i have many nodes, how to bulk register node in lora-app-server?

![image](https://user-images.githubusercontent.com/22229469/29108769-9284d250-7d0a-11e7-9f0a-e2db54e99b45.png)

Thanks

**Comment by siscia** [comment]
The fastest way would be using the REST API exposed.

Start doing a login and save the token.
At this point pass the token at each request in the header.

You should be able to do everything asynchronously.

If register for otaa you still need to do a join...

**Comment by brocaar** [comment]
I'll close this issue as https://github.com/brocaar/lora-app-server/issues would be a better place. But as @siscia mentioned, currently the API would be the best way to do this.
