### ISSUE TITLE
using JSON REST api

### ISSUE THREAD

**Issue by monkmahadeva** [brocaar/loraserver#224]
Hi brocaar, I want to know the url to perform the httpconnection inorder to retrieve the JSON body. Our lora-app-server is running on localhost:8080 and our java application is running on http://localhost:8089/lora_project. Thank you.

**Comment by brocaar** [comment]
Please see https://docs.loraserver.io/lora-app-server/integrate/rest/. For further support related questions, please use https://forum.loraserver.io.
