### ISSUE TITLE
Maybe dead lock

### ISSUE THREAD

**Issue by tornodo** [brocaar/loraserver#229]
After running for a time ,then I send message , the  gateway-bridge running fine, but the loraserver and lora-app-server seems dead lock for no log output. I don't know what i can do. I keep my computer running all night.
![deadlock](https://user-images.githubusercontent.com/4067864/29512445-d0b6360c-8694-11e7-85f3-18518d9e2b02.PNG)

**Comment by brocaar** [comment]
Please note that it could also be the connection from LoRa Server to your MQTT broker. Which versions of the components are you using?
