### ISSUE TITLE
Multiple end-nodes join issue

### ISSUE THREAD

**Issue by Mehradzie** [brocaar/loraserver#23]
Hi guys,

After whole lot of wrestling with bits and peices of LoRa today I was trying to connect a 2nd end-node to LoraServer, and surprisingly, when I have one end-node already joined, the 2nd one refuses to join.

I have tested them with the Loraserver which comes with Multitech AEP Conduit and they connected fine, so in this instance either Multitech mDot end-node library and Multitech Conduit gateway both have the same bug which enables me to connect multiple end-nodes or something isn't set up in the brocaar/loraserver right.

Tomorrow I am going to try flashing the Multitech mDots with Semtech open source LoraWAN firmware to see if I'll have the same issue but meanwhile I thought, I'll ask this and you'll get it see it tonight.

atm, on the Loraserver GUI I have set up a single Application (0000000000000001) and my end-nodes have two different Appkeys (00000000000000000000000000000001 and 00000000000000000000000000000002) and each one individually connects to the server alright but not together.

let me now what you think about this,

Cheers

Mehrad

**Comment by Mehradzie** [comment]
[Update]
LoRaWAN semtech code for end-nodes seems to have a similar issue. One node hugs the server and non of the others can join. I am not even sure where to start to bug-fix this.

**Comment by brocaar** [comment]
Hmmm... that is odd. I've beed doing tests in the past with multiple nodes, but maybe a regression happend during some refactoring or changes? I'll do some testing at my side to see if I can reproduce this issue and find a fix.

**Comment by VirTERM** [comment]
I don't have such problem. Running multiple nodes through more than one gateway

**Comment by Mehradzie** [comment]
I've put a 10s delay before sending the packets after the join and now the rest of the nodes (3 at the same time) join, no problem. gonna cram in another 10 to see how it will handle it. How frequently you guys have been sending packets for your testing?

I am guessing we are still dealing with the sx1310 single buffer issue with the current basic/gps/etc packet forwarder which doesn't have any queue system and packets are writing on top of each-other. :space_invader:

**Comment by VirTERM** [comment]
For testing i send packet every 2
mins. Usually, multiple gateways and couple of nodes per gateway.

**Comment by ivajloip** [comment]
I have also tested with multiple devices without a problem. In my case there was a large time difference between the join requests and thus the buffer size was not an issue for me.

**Comment by Mehradzie** [comment]
Thanks guys. I have figured out the during the 5 second wait for the join response, the request was getting over written by another node's 2 second data. Hope they implement the queue on the stable edition of packet forwarder soon.

**Comment by VirTERM** [comment]
Actually, I run some tests, and i can see that there is a problem. If i send even a couple of join requests via the same gateway, at least one of them will fail....

**Comment by brocaar** [comment]
Did you already try the new packet_forwarder (v3) with the
lora-semtech-bridge (v2)? The new packet_forwarder should fix some issues
regarding to scheduling.
