### ISSUE TITLE
Schedule downlink

### ISSUE THREAD

**Issue by monkmahadeva** [brocaar/loraserver#234]
This is the response that we are fetching when we achieve in a downlink . As mentioned it comes with the status 200 with an empty result set also.

![screenshot from 2017-08-28 16-19-07](https://user-images.githubusercontent.com/13939810/29772042-7fcc41c0-8c14-11e7-9176-73fc856d76f5.png)

Although we are trying to check a confirmation from the gateway side,Could you please tell us the right approach for this .

**Comment by monkmahadeva** [comment]
Also the logs for lora-app-server show that the packet is en queued. Although When try the downlink the total number of queue elements stay the same. So i guess downlink is not happening right??

![screenshot from 2017-08-28 17-20-51](https://user-images.githubusercontent.com/13939810/29772349-07378b3c-8c16-11e7-809f-95daf799c513.png)

**Comment by monkmahadeva** [comment]
{
{
{
  "id"="1",
   "devEUI"="......"
    "pending" = "false"
     ......
     ......
}
}
}
What does the pending parameter in the JSON body of api https://localhost:8080/api/nodes/[MAC]/queue mean??

**Comment by brocaar** [comment]
Please use https://forum.loraserver.io for support questions 👍

**Comment by monkmahadeva** [comment]
https://forum.loraserver.io/t/schedule-downlink/80
