### ISSUE TITLE
otaa join failed 

### ISSUE THREAD

**Issue by tornodo** [brocaar/loraserver#238]
first thanks for your project.
I used all the code is the newest.
I can seen lora-app-server log join-request accepted, but the node join failed.
the command is:
loraserver 
./loraserver --net-id 010203 --band CN_470_510 --postgres-dsn postgres://loraserver_ns:loraserver_ns@localhost/loraserver_ns?sslmode=disable --db-automigrate --gw-mqtt-server tcp://127.0.0.1:1883 --log-node-frames --gw-server-jwt-secret Y301pq2kbuKbZHHlrGCsIoiMf7UJAnlEerv8OHYD93Q=

lora-app-server
./lora-app-server --postgres-dsn postgres://loraserver_as:loraserver_as@localhost/loraserver_as?sslmode=disable --db-automigrate --mqtt-server tcp://127.0.0.1:1883 --log-level 5 --jwt-secret Y301pq2kbuKbZHHlrGCsIoiMf7UJAnlEerv8OHYD93Q= --http-tls-cert server.crt --http-tls-key server.key

![1](https://user-images.githubusercontent.com/4067864/30011057-12b7ecf8-9167-11e7-8443-3cf3103b2104.png)

**Comment by brocaar** [comment]
Please use https://forum.loraserver.io/ for support questions.
