### ISSUE TITLE
Class C broadcast

### ISSUE THREAD

**Issue by borisbstyle** [brocaar/loraserver#240]
### Is this a bug or a feature request?
feature request

I am not aware of any way to do multicast / broadcast to Class C devices, but there are already some documents describing this idea.
https://docs.google.com/viewerng/viewer?url=https://www.dropbox.com/s/877v31p0r1p056c/LoRa%2520Bootcamp%2520intelliLight%2520presentation.pdf?dl%3D1

Is there already a way to send downlink messages that will be picked up by all class C devices?

**Comment by brocaar** [comment]
Please see #227.
