### ISSUE TITLE
Changing default channels (chMask)

### ISSUE THREAD

**Issue by borisbstyle** [brocaar/loraserver#242]
### Is this a bug or a feature request?
feature

This is basically a question weather it is possible to send mac command to all or some nodes that the default channel layout has been changed. I was not able to find this in any of the manuals?
I see this is only happening when node is reactivated and during ADR, but can it be forced at anytime?

**Comment by brocaar** [comment]
When you change the channels (`--enabled-channels`) LoRa Server will automatically issue `LinkADRReq` mac-commands. Note that this only works for the "default" channels, the channels that are by definition known to the node. E.g. in the US there are 72 channels, for EU there are 3. This works independent of ADR (although some nodes reject these mac-commands when ADR is disabled, this is incorrect behaviour).

LoRa Server will disable channels that are part of the `--extra-channels` (CFList channels), but will not re-activate them (currently) as it is unknown if the node is aware of these channels. A future feature could be that LoRa Server will send new channel-configuration to the node for the channels part of the CFList and will ask the node to activate these channels.

**Comment by borisbstyle** [comment]
ok I am just trying to understand this part...
https://github.com/brocaar/lorawan

And than particularly these MAC commands. How can I use these?
`* LinkCheckReq
* LinkCheckAns
* LinkADRReq
* LinkADRAns
* DutyCycleReq
* DutyCycleAns
* RXParamSetupReq
* RXParamSetupAns
* DevStatusReq
* DevStatusAns
* NewChannelReq
* NewChannelAns
* RXTimingSetupReq
* RXTimingSetupAns
* Proprietary commands (0x80 - 0xFF) can be registered with RegisterProprietaryMACCommand`

**Comment by borisbstyle** [comment]
I am going to close this issue since my actual problem has to do with versioning of nodes
https://github.com/brocaar/loraserver/issues/192

**Comment by borisbstyle** [comment]
@brocaar Sorry for coming back to this issue, but the behaviour described above doesnt seem correct.


Here some logging:
First ADR command
![image](https://user-images.githubusercontent.com/10757508/34206425-c8e7fe50-e586-11e7-87a2-afb623fc5f69.png)


Response from device (Note there is a channel mask NACK as device doesn't know the extra channels):
![image](https://user-images.githubusercontent.com/10757508/34206441-d8995f56-e586-11e7-8fac-a9e9c868e2b2.png)

The next message from server. And this goes on and on. Instead of this loraserver should start programming the extra channels according to your description?:
![image](https://user-images.githubusercontent.com/10757508/34206469-f2261a90-e586-11e7-8cbb-53094ae2a510.png)

**Comment by kuripiiritus** [comment]
Currently it seems, that with join the channel list works ok.  When the ADR is sent then the chmask 0x07 is sent on, which kills the extra channels configured in the server, gateway and node. After this the node only shoots on 3 default channels.  Is there a workaround / fix for that. Would not like to use 3 channels, but not also disable ADR also.
