### ISSUE TITLE
Usernames to support email format

### ISSUE THREAD

**Issue by fyrcyning** [brocaar/loraserver#252]
Hi, 

Wanting to use email addresses as usernames but the format requirements don't support this, hoping that this would be a simple change that you would be willing to accommodate as it would help me to ensure users can easily remember their login details.

Cheers, 

Blair

**Comment by brocaar** [comment]
Please note that user accounts are specific to LoRa App Server, not LoRa Server. Would you therefore mind re-creating the issue there? https://github.com/brocaar/lora-app-server
