### ISSUE TITLE
Node can join the network but can't receive any data

### ISSUE THREAD

**Issue by saboohajaz** [brocaar/loraserver#255]
Hi,

The node is joining the network without an issue but i cant see any any data sent by the node after joining

![image](https://user-images.githubusercontent.com/30172152/31696623-21d07394-b3fa-11e7-8103-714afb96067e.png)

Bridge
![bridge](https://user-images.githubusercontent.com/30172152/31696639-357f6a9e-b3fa-11e7-980e-800d7ae9e22b.png)

loraserver
![image](https://user-images.githubusercontent.com/30172152/31696650-4b9d84b4-b3fa-11e7-8d00-df09795a3d7f.png)

lora-app-server
![image](https://user-images.githubusercontent.com/30172152/31696658-51b76f68-b3fa-11e7-91e0-4d67bed117dd.png)

mqtt
![image](https://user-images.githubusercontent.com/30172152/31696659-5841ac04-b3fa-11e7-9661-8d7bda4a0591.png)

I tried the same node with Multitech gateway. Multitech can receive data. But only after i reset the node one or two times
I am using STM32 Nucleo + SX1272 shield

**Comment by saboohajaz** [comment]
The pictures above are for ABP activation.
For OTAA the node was joining but can see any data after the successful join request/accept

**Comment by saboohajaz** [comment]
Furthermore,
I am using 
sudo mosquitto_sub -t "#"

Somehow following is not working
mosquitto_sub -t "application/1/#" -v

**Comment by brocaar** [comment]
See your first screenshot, the node is not sending any `fPort` and `frmPayload`, so LoRa Server does not send anything to LoRa App Server as there is nothing to forward. `fPort > 0` means an application payload.
