### ISSUE TITLE
Empty CFList in JoinAccept

### ISSUE THREAD

**Issue by x0y1z2** [brocaar/loraserver#257]
I use EU_863_870 frequency plan. I created channel configuration with 5 extra channels, and assigned id to my gateway. But server sends JoinAccept with empty CFList. And it sends ADR packets with chMask, where activated only 3 channels.
In channel configuration field "Enabled channels" contains "0, 1, 2", because with other numbers I have error "invalid channel (code: 3)".

**Comment by brocaar** [comment]
You need to use the `--extra-frequencies` flag, see also: https://docs.loraserver.io/loraserver/install/config/

**Comment by x0y1z2** [comment]
Yes, it works.
For what purposes I can use extra channels in web-interface?

**Comment by brocaar** [comment]
That is when you're using https://docs.loraserver.io/lora-channel-manager/overview/, to manage your gateway channel config.
