### ISSUE TITLE
Channel configuration for node

### ISSUE THREAD

**Issue by x0y1z2** [brocaar/loraserver#259]
With multichannel gateways it can be usefull to send different CFLists in JoinAccept for nodes.

**Comment by brocaar** [comment]
Yes, I agree, this is currently not (yet) possible.

**Comment by brocaar** [comment]
I probably won't implement this. I've just merged an updated way to manage channel configuration into the master branch. This will allow you to configure up to 16 channels in total: https://github.com/brocaar/loraserver/blob/master/docs/content/features/channel-configuration.md.
