### ISSUE TITLE
ADR without fOpts

### ISSUE THREAD

**Issue by x0y1z2** [brocaar/loraserver#260]
Server usually sended normal ADR with fOpts to node, and node used low power, set from ADR. But 2 days ago server sended ADR with empty fOpts and device began to transmit on full power.
After this packet server didn't sended ADR packets, although ADR interval exceeded.

**Comment by brocaar** [comment]
Could you post a screenshot of this frame? I'm not sure what you mean with:

> server sended ADR with empty fOpts

**Comment by x0y1z2** [comment]
Frame with fOpts: null
![empty_fopts](https://user-images.githubusercontent.com/33101482/32136497-285f43f0-bbfe-11e7-9cd7-b58eb5c693e2.png)
Frame with normal fOpts (first ADR frame after device reactivating)
![good_fopts](https://user-images.githubusercontent.com/33101482/32136498-28828b1c-bbfe-11e7-888a-396b49953eba.png)

**Comment by brocaar** [comment]
> But 2 days ago server sended ADR with empty fOpts

The network-server only sends a LinkADRReq when it things it is needed to change the data-rate or tx-power of your node and on the interval. From the above screenshot I can tell if it should kick in or not, but I don't think this is a bug.

In case you would discuss this further, please create a topic at https://forum.loraserver.io :-)
