### ISSUE TITLE
Multiple errors at the step : LoRa Server Debian repository

### ISSUE THREAD

**Issue by assran666** [brocaar/loraserver#264]
Hi, I am facing a problem during the installation of lora server on my VM. I'm at the step :
"LoRa Server Debian repository" that you can find here : https://docs.loraserver.io/loraserver/install/debian/

I did theses 3 commands : 

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1CE2AFD36DBCCA00
export DISTRIB_ID=`lsb_release -si`
export DISTRIB_CODENAME=`lsb_release -sc`
sudo echo "deb https://repos.loraserver.io/${DISTRIB_ID,,} ${DISTRIB_CODENAME} testing" | sudo tee /etc/apt/sources.list.d/loraserver.list

and now when I am executing the last one :  sudo apt-get update

here what my screen is showing : 

<img width="1061" alt="capture d ecran 2017-10-30 a 15 01 01" src="https://user-images.githubusercontent.com/33225837/32174826-44b5cd36-bd83-11e7-8ef9-ee999284fb61.png">

Have you and idea on how I can fix theses errorq ? 

Thanks :)

**Comment by brocaar** [comment]
Please don't use the GitHub issues for support questions, https://forum.loraserver.io is a better place. Also, your error is related to your PostgreSQL repository.
