### ISSUE TITLE
[Feature] Ability to move nodes/applications.

### ISSUE THREAD

**Issue by mihaispataru** [brocaar/loraserver#265]
### Is this a bug or a feature request?
Feature

### What did you expect?
1. Possibility to move nodes from an application to another as admin or as user from an organization
2. Possibility to move applications with nodes from an organization to another as admin.

**Comment by iegomez** [comment]
This should probably be asked at the lora-app-server repo: https://github.com/brocaar/lora-app-server/issues.

**Comment by brocaar** [comment]
Yes, please create this issue there.

(Please note that this feature might not be possible, as nodes of application 1 could be on a different network-server than the nodes of application 2.)
