### ISSUE TITLE
Source code compilation error

### ISSUE THREAD

**Issue by Sivan-wang** [brocaar/loraserver#266]
### Is this a bug or a feature request?

When I compile this error message:
 cmd / loraserver / main.go: 358: 14: undefined: migrations.AssetDir.
I found that 'migrations_gen.go' has no implementation of 'AssetDir'

### How can your issue be reproduced?

I can annotate this statement so that I can compile it

### Could you share your log output?

**Comment by brocaar** [comment]
Please create a topic at https://forum.loraserver.io as this is more a support question, it seems to be related to your local setup (else it would have broken the build pipeline).

**Comment by Sivan-wang** [comment]
Thanks, I found a problem with my 'go-bindata' program version. Updated normal.
