### ISSUE TITLE
Scripts for Gentoo

### ISSUE THREAD

**Issue by Ektanoor** [brocaar/loraserver#270]
Hi

I use Gentoo and OpenRC (init.d) so I had to modify the install and init scripts, both for loraserver and lora-app-server. Is there any interest/need for them? If so, where I can send them?

Note that I could test them on OpenRC only. The Systemd variant is present but I don't have an equivalent Gentoo to test them.

**Comment by brocaar** [comment]
Great you got it working on Gentoo :-) I'm a bit reserved in adding these to the repository, as I don't have experience with using Gentoo, and it means I need to maintain these scripts too. However I think the forum could be a great place to post these scripts and share how you did your setup (Setup and configuration category): https://forum.loraserver.io. Thanks in advance!
