### ISSUE TITLE
Bug in the Lora App Server interface : wrong payload data after fPort

### ISSUE THREAD

**Issue by lucdioc** [brocaar/loraserver#275]
### Is this a bug or a feature request?
It's a bug : on the "Raw frame logs" of one of our nodes, the payload sent in fPort 20 by the node is shown as a value, for example "eISO" when subscribing to the topic of the node through Mosquitto, the payload on the fPort 20 is "AQCt"

### What did you expect?
I expected to read:
- bytes "AQCt"
I read:
- bytes "eISO"
### What happened?
I don't know ?

### What version are your using?
Latest version of Lora App Server

### How can your issue be reproduced?
Each time I use a PIR sensor from Ascoel Gap supplier

**Comment by brocaar** [comment]
As mentioned on the raw frame-log page, all you see is the raw data as transmitted over the air. Thus the data you see is encrypted. The data published over MQTT (or the HTTP integration) is decrypted.
