### ISSUE TITLE
Rules of confirmed downlinks retransmition if no ACK from node

### ISSUE THREAD

**Issue by sputnik-alarm** [brocaar/loraserver#277]
### Is this a bug or a feature request?
Feature.

### What did you expect?
Whant server to retransmit confirmed downlinks if node not answering.

### What happened?
Server doesn't retransmit confirmed downlinks.

**Comment by sputnik-alarm** [comment]
Is there any rules, of how the confirmed downlink with ack getting timeout will be retransmitted again?
Does server generally makes this retransmition? How much attempts will make server? Is there any dependencies on working in different LoRa classes?

**Comment by brocaar** [comment]
When using the latest LoRa Server version, it will never re-transmit a confirmed downlink. Also LoRa Server would not be able to do so, as the payload is encrypted using the downlink frame-counter, which can not be re-used.  Please see: https://forum.loraserver.io/t/release-lora-app-server-0-15-lora-server-0-25/492.
