### ISSUE TITLE
Multicast Downlink to XDOT devices

### ISSUE THREAD

**Issue by habbasi3** [brocaar/loraserver#279]
Hi,

Thank you for this great work. I would like to send a multicast downlink message to multiple XDots through a single Multitech gateway. From your previous post, I understand that I should setup a multicast node using LoRa AppServer (using ABP and Class C) and configure all of my nodes with this multicast configuration (DevAddr, NwkSKey, AppSKey, etc...) to send a multicast downlink. However, XDots have factory defined DeviceEUI (which cannot be changed). So, how can I setup multiple XDOTs to have the same DevAddr or send a multicast message to multiple XDots with different DeviceEUI ?

Thanks a lot

**Comment by brocaar** [comment]
Mind to re-post this question in the forum? https://forum.loraserver.io. Other people might benefit from the answer too :-) Github issues are fine for bugs, but after closing an issue the answer becomes "invisible" making it less ideal for a knowledgebase.

**Comment by habbasi3** [comment]
Hi,

I have posted the question in the loraserver forum. Please check.

Thanks a lot
