### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by l0ng09** [brocaar/loraserver#280]
vsersion:
commit 887bb2f6bb5015c18e519a3de3e422ad056fe9f4
Author: Orne Brocaar <info@brocaar.com>
Date:   Sat Dec 16 11:04:22 2017 +0100

loraserver

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8cb395]

    goroutine 66 [running]:
    github.com/brocaar/loraserver/internal/api.(*NetworkServerAPI).GetFrameLogsForDevEUI(0xe275d0, 0x7fdd6bd9b788, 0xc4202fa540, 0xc4201d6220, 0xe275d0, 0x428c99, 0xc4201a86f0)
            /home/ryan/go/src/github.com/brocaar/loraserver/internal/api/network_server.go:908 +0x4c5
    github.com/brocaar/loraserver/api/ns._NetworkServer_GetFrameLogsForDevEUI_Handler(0xa54be0, 0xe275d0, 0x7fdd6bd9b788, 0xc4202fa540, 0xc420778320, 0x0, 0x0, 0x0, 0x0, 0x0)
            /home/ryan/go/src/github.com/brocaar/loraserver/api/ns/ns.pb.go:3885 +0x279
    github.com/brocaar/loraserver/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200a83c0, 0xdc2940, 0xc4200d8000, 0xc4207bc000, 0xc4207502a0, 0xe002b8, 0xc4202fa600, 0x0, 0x0)
            /home/ryan/go/src/github.com/brocaar/loraserver/vendor/google.golang.org/grpc/server.go:776 +0xab4
    github.com/brocaar/loraserver/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200a83c0, 0xdc2940, 0xc4200d8000, 0xc4207bc000, 0xc4202fa600)
            /home/ryan/go/src/github.com/brocaar/loraserver/vendor/google.golang.org/grpc/server.go:976 +0x1528
    github.com/brocaar/loraserver/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc42008a2e0, 0xc4200a83c0, 0xdc2940, 0xc4200d8000, 0xc4207bc000)
            /home/ryan/go/src/github.com/brocaar/loraserver/vendor/google.golang.org/grpc/server.go:546 +0x9f
    created by github.com/brocaar/loraserver/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
            /home/ryan/go/src/github.com/brocaar/loraserver/vendor/google.golang.org/grpc/server.go:544 +0xa1

lora-app-server

      INFO[0010] transport: http2Client.notifyError got notified that the client transport was broken EOF. 
      INFO[0010] grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::1]:8000: getsockopt: connection refused"; Reconnecting to {localhost:8000 <nil>} 
      INFO[0011] grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::1]:8000: getsockopt: connection refused"; Reconnecting to {localhost:8000 <nil>} 
      INFO[0013] grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::1]:8000: getsockopt: connection refused"; Reconnecting to {localhost:8000 <nil>} 
      INFO[0016] grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::1]:8000: getsockopt: connection refused"; Reconnecting to {localhost:8000 <nil>} 
     2017/12/27 14:45:59 http2: server: error reading preface from client 192.168.1.111:64978: timeout waiting for client preface
     INFO[0020] grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp [::1]:8000: getsockopt: connection refused"; Reconnecting to {localhost:8000 <nil>} 
what can I do to solve this problem ,any help will be great ,thanks

**Comment by brocaar** [comment]
Thanks for reporting, I found out where the error comes from: https://github.com/brocaar/loraserver/blob/master/internal/api/network_server.go#L908

`.Time` was turned into a pointer by https://github.com/brocaar/loraserver/commit/5981fbf925ace5499f191543fd3cb8b3122574aa and I overlooked to handle this case.
