### ISSUE TITLE
multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by SnailQuick** [brocaar/loraserver#285]
### Is this a bug or a feature request?
bug
### Could you share your log output?
Compiler output:
.\device_profile.go:38:48: multiple-value uuid.NewV4() in single-value context

code is " dp.DeviceProfile.DeviceProfileID = uuid.NewV4().String() "

**Comment by brocaar** [comment]
https://forum.loraserver.io/t/compiling-the-lora-server-source-code/663
