### ISSUE TITLE
The problem of connection lora-server and lora-app-server

### ISSUE THREAD

**Issue by SoHyunYang** [brocaar/loraserver#286]
I want to use lora server version 14.1 and lora-app-server 5.0 version. I tried to run both source code using the docker-compose command, but I found that the two are not connected and run separately. At this point, the mqtt server used by both source code is set to have the same ip and port. I think I  need to configure --as-server value (hostname: port of the application-server api) and --ns-server value (hostname: port of the network-server api server).
But this is the first time that i have used docker-compose, i don't know how to see the ip address and port of the lora server and app-server when I run these source throgh docker-compose.
I wonder if there is a way to define the ip address of the docker or the docker-compose command to check the ip address.

Thank you.

**Comment by brocaar** [comment]
This is a support question, please use https://forum.loraserver.io. Also, we provide a ready-to-use `docker-compose.yml` file which you can use to get started: https://docs.loraserver.io/install/docker/.
