### ISSUE TITLE
multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by SnailQuick** [brocaar/loraserver#287]
### Is this a bug or a feature request?
bug
I'm gonna put the code in there into $GOPATH/src/github.com/brocaar/loraserver.
I can compile it at version 0.23.1, but compile 0.23.2 can go wrong.

Compiler output:
.\device_profile.go:38:48: multiple-value uuid.NewV4() in single-value context
How to solve it?
![image](https://user-images.githubusercontent.com/32405301/35480561-a8d6f2ea-044b-11e8-92f7-42facd78cf6b.png)

What development tools do you use to compile?
Thank you!

**Comment by brocaar** [comment]
Please use the forum for support related questions as others might benefit from the answer too. There is already a topic about compiling the LoRa Server source-code: https://forum.loraserver.io/t/compiling-the-lora-server-source-code/663. Thanks!
