### ISSUE TITLE
Error at lora server's logs

### ISSUE THREAD

**Issue by ktsakos** [brocaar/loraserver#288]
Jan 30 12:22:49 lora loraserver[1181]: time="2018-01-30T12:22:49Z" level=error msg="processing rx packet error: get node-session error: node-session does not exist or invalid fcnt or mic" data_base64="gFY0EjoAAAABnqTehL37mOh5EQ8="

What may be the problem?
May i have to declare somewhere my node's NewSKey and AppSKey?
My NODE supports activation by personalization ABP

**Comment by brocaar** [comment]
Please see: https://forum.loraserver.io/search?q=invalid%20fcnt%20or%20mic.
