### ISSUE TITLE
trying to change defaultTXpower value.

### ISSUE THREAD

**Issue by sergiopp** [brocaar/loraserver#290]
### Is this a bug or a feature request?
bug (I hope not :) )
### What did you expect?
I was expecting to change the defaultTXpower value but something happened.
### What happened?
It couldn't compile.
### What version are your using?
we were using the 0.23.3 tag but now we are using master.
### How can your issue be reproduced?
I made a fork from your 0.23.3 tag but when the compiling process started this error appeared on the screen.
### Could you share your log output?
internal/maccommand/maccommand.go:73:71: cannot use linkADRPayloads (type []"github.com/Frankz/loraserver/vendor/github.com/Frankz/lorawan".LinkADRReqPayload) as type []"github.com/Frankz/loraserver/vendor/github.com/brocaar/lorawan".LinkADRReqPayload in argument to common.Band.GetEnabledChannelsForLinkADRReqPayloads
make: *** [Makefile:10: build] Error 2
ERROR: Service 'loraserver' failed to build: The command '/bin/sh -c make' returned a non-zero code: 2

**Comment by brocaar** [comment]
I'm unable to give community support on custom modifications. Please see https://docs.loraserver.io/loraserver/community/source/ as a starting point. Also the compiler error might give you some hints :-)
