### ISSUE TITLE
Using Cayenne over loraserver implementation?

### ISSUE THREAD

**Issue by FrancoisLefevre12** [brocaar/loraserver#291]
Hi everyone,

I would like to know if there is a way or not using the web application MyDevices Cayenne over the server implementation? 
The Lora App Server is really fine but I just want the possibility to have my payloads decrypted as I can manipulate data into dashboards or graphs, without having to administrate my network with Cayenne.
I know some people did this kind of thing but I just did not find out to do that. 

Before, I was using the ELK stack to analyze received data but this service does not have a MQTT plugin to process data so I'm trying something else.

Thank you for your attention,
François

**Comment by brocaar** [comment]
This features is already provided by the latest LoRa App Server version. Simply use the Cayenne LPP coded in your application settings.
