### ISSUE TITLE
implementation of TDOA and RSSI based time domain geolocation

### ISSUE THREAD

**Issue by narioinc** [brocaar/loraserver#294]
### Is this a bug or a feature request?
This is a feature request.

### What did you expect?
Is there a plan for the Lora server to implement the new TDOA and RSSI geolocation feature announced by Semtech during the TTN conference ?

**Comment by gillespilloudwyres** [comment]
Hi,

As I have understood, the new precise-timestamp sent by semtech chip will be under licence, and an decrypt key, will be necessary to have the precise timestamp requested to do TDOA. Have you hear that ?

**Comment by narioinc** [comment]
Yes, I haven't yet looked at the complete business model being advertised by semtech for their blob license. But I guess we will soon find out once we get boards that support the feature. I'll keep this issue updated when I get additional information.

**Comment by narioinc** [comment]
TTN is yet to get a full fledged implementation out...so I am still waiting for OEM to support the feature.

**Comment by brocaar** [comment]
Support for an external geolocation server has been merged into the `master` branch. I'll announce a geolocation server (which integrates with Collos) soon :)

**Comment by brocaar** [comment]
Please see https://forum.loraserver.io/t/release-lora-app-server-v2-2-0-lora-geo-server-v2-0-0/2246.
