### ISSUE TITLE
problem of  TLS certificate on docker

### ISSUE THREAD

**Issue by guhongyeying** [brocaar/loraserver#299]
Hello,  I use docker to run lorasever app demo when I Add network-server is wrong. I don't know that the configuration of TLS certificates is in the case of docker. You can help me?
(https://172.16.3.92:8080/#/network-servers/create)

**Comment by brocaar** [comment]
Using docker or not doesn't change the configuration. Please see https://docs.loraserver.io/lora-app-server/use/network-servers/. Please use https://forum.loraserver.io for support questions.

**Comment by guhongyeying** [comment]
ok！ thanks
