### ISSUE TITLE
regional parameters RU864_870

### ISSUE THREAD

**Issue by VahrushevSA** [brocaar/loraserver#304]
Hello Brocaar!
I ask to compile a new build loraserver on the basis of regional parameters RU864_870
[LoRaWAN Regional Parameters v1.1rB - Final.pdf](https://github.com/brocaar/loraserver/files/1787957/LoRaWAN.Regional.Parameters.v1.1rB.-.Final.pdf)

**Comment by krivorotko** [comment]
Hello Brocaar!
We also have an interesting build with a regional parameters RU864_870

**Comment by brocaar** [comment]
This has already been merged in the latest release :-)
