### ISSUE TITLE
List unknown devices via API

### ISSUE THREAD

**Issue by carlberg74** [brocaar/loraserver#305]
Possible future feature.
Would be nice if I could use the API to query to find devices that are not known to the loraserver.
"Devices that has been seen in the network".
I understand that this could be a massive amount of devices, but still nice feature when you are looking for a specific device.

**Comment by carlberg74** [comment]
Don't seem possible to use the MQTT, as the gateway/# is too early and the application/# is too late.

The workaround I have created was a script that tails the lora-app-server log and send it to a mqtt called unauthorized. Json message with server, timestamp and deveui etc.
I also added to detect devices that sends wrong mic or other error.

Maybe the loraserver should just have a separate mqtt queue for these type of messages; "unauthorized devices"?
So the sysadmin can hook up to this queue and process them if he/she likes or just ignore them.

My message contains devEui, server, timestamp, gateway mac and some type of status with why.
ex. 
{ time="2018-03-08T23:18:45Z" server="LoraServer001" mac="aabbccddee11223344"  devEui="a81758fffeaabbcc" status="notFound" }
{ time="2018-03-08T23:18:47Z" server="LoraServer001" mac="aabbccddee11223344" devEui="a81758fffebbccdd" status="invalidMic" appEui="0000000000000005" }

**Comment by brocaar** [comment]
Are you looking for the `DevEUI` or the `DevAddr`? The first is only available in the join-request message, the latter in all other messages.

Note that both could be extracted from the `gateway/#` mqtt topic and using the https://godoc.org/github.com/brocaar/lorawan library.

**Comment by carlberg74** [comment]
I guess only the DevEui during a Join-Request and that fails for some reason. 
This to find devices that should have been added to the server or to spot the devices that have been wrongly configured or added to the server.

Thanks, I will have a look at the library.

**Comment by brocaar** [comment]
Alternatively if you think the current log is not sufficient, we could also improve that. So that you can process the logs to look for devices that are not yet provisioned. https://forum.loraserver.io/t/automatically-create-device-on-join/983 could be an other option.

**Comment by brocaar** [comment]
I will close this issue for now. Keeping an eye on the performance, I don't think it is a good idea to store the DevEUIs of all failed join-requests as with neighboring networks, this could end up in a huge list of devices.

Personally I think it is a better idea to monitor the behavior of known devices. E.g. set an alarm (which you can do in Grafana for example) when a known device has been inactive for too long.
