### ISSUE TITLE
DevEUI Uniqueness

### ISSUE THREAD

**Issue by 1995parham** [brocaar/loraserver#306]
What do you think about the following feature?

DevEUI must be unique per application by considering AppEUI instead system-wide uniqueness.

**Comment by brocaar** [comment]
This will not work. The AppEUI will be renamed to JoinEUI (already happened in LoRaWAN 1.1) and will be used to identify the entity which handles the OTAA join-request. Therefore the DevEUI must be globally unique.

**Comment by 1995parham** [comment]
Thanks for your answer so you think there is no way for providing a way for joining two things with same DevEUI in loraserver.io?

**Comment by brocaar** [comment]
No, that won't be supported as it would make a lot of things more complex than needed. Luckily the 64 bit address space should give you enough DevEUIs I hope 😉
