### ISSUE TITLE
Gateway statistics not showing

### ISSUE THREAD

**Issue by bocajim** [brocaar/loraserver#309]
I am testing your LoRa server, and its working great, but I have an issue with the Gateway view, I'm not seeing any information under "Last seen (stats)", or the Frames sent/received per day graphs, even though I know data is flowing.

Is there somthing I need to enable for this functionality?

I'm running loraserver 0.25.1 and lora-app-server 0.18.2 and lora-gateway-bridge 2.3.2

**Comment by brocaar** [comment]
Could you post your question at https://forum.loraserver.io? The question might already been asked / answered :-)
