### ISSUE TITLE
ping database error

### ISSUE THREAD

**Issue by zhoubx123** [brocaar/loraserver#316]
Hi，when run the command : systemctl start loraserver,
there is : 
08 09:39:26  loraserver[22140]: time="2018-04-08T09:39:26+08:00" level=info msg="disabling all channels"
 08 09:39:26  loraserver[22140]: time="2018-04-08T09:39:26+08:00" level=info msg="enabling channels" channels="[0 1 2 3 4 5 6 7]"
 08 09:39:26  loraserver[22140]: time="2018-04-08T09:39:26+08:00" level=info msg="setup redis connection pool" url="redis://localh
 08 09:39:26  loraserver[22140]: time="2018-04-08T09:39:26+08:00" level=info msg="connecting to postgresql"
 08 09:39:26  loraserver[22140]: time="2018-04-08T09:39:26+08:00" level=error msg="ping database error, will retry in 2s: pq: pass

who can help me ?

**Comment by brocaar** [comment]
Please use the forum for support questions :-) https://forum.loraserver.io/search?q=ping%20database%20error
