### ISSUE TITLE
SyntaxError: JSON.parse: bad control character in string.   While I inspect the json, which comes from app-server, I got following:  "rxInfo":[{ and this object can't decoded, but  "txInfo":{   successefully  decoded, is it a bug?

### ISSUE THREAD

**Issue by shepiloff** [brocaar/loraserver#317]

**Comment by brocaar** [comment]
* Please create the issue at the repository to which the issue is related, which is LoRa App Server
* Please use the provided template for creating issues. Without any clue how I can reproduce your issue, I don't see a way how I can help you.
