### ISSUE TITLE
error  at installation

### ISSUE THREAD

**Issue by Night19** [brocaar/loraserver#319]
Does anyone know why I get this message?
Apr 14 09:28:35 ip-172-31-44-120 lora-app-server[16790]: time="2018-04-14T09:28:35Z" level=fatal msg="read configuration file error" error="While parsing config: (42, 5): keys cannot contain : character"
Apr 14 09:28:35 ip-172-31-44-120 systemd[1]: lora-app-server.service: Main process exited, code=exited, status=1/FAILURE
Apr 14 09:28:35 ip-172-31-44-120 systemd[1]: lora-app-server.service: Unit entered failed state.
Apr 14 09:28:35 ip-172-31-44-120 systemd[1]: lora-app-server.service: Failed with result 'exit-code'.
Apr 14 09:28:35 ip-172-31-44-120 systemd[1]: lora-app-server.service: Service hold-off time over, scheduling restart.
Apr 14 09:28:35 ip-172-31-44-120 systemd[1]: Stopped LoRa App Server.
Apr 14 09:28:35 ip-172-31-44-120 systemd[1]: Started LoRa App Server.
Apr 14 09:28:35 ip-172-31-44-120 lora-app-server[16797]: time="2018-04-14T09:28:35Z" level=fatal msg="read configuration file error" error="While parsing config: (42, 5): keys cannot contain : character"
Apr 14 09:28:35 ip-172-31-44-120 systemd[1]: lora-app-server.service: Main process exited, code=exited, status=1/FAILURE
Apr 14 09:28:35 ip-172-31-44-120 systemd[1]: lora-app-server.service: Unit entered failed state.
Apr 14 09:28:35 ip-172-31-44-120 systemd[1]: lora-app-server.service: Failed with result 'exit-code'.
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: lora-app-server.service: Service hold-off time over, scheduling restart.
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: Stopped LoRa App Server.
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: Started LoRa App Server.
Apr 14 09:28:36 ip-172-31-44-120 lora-app-server[16804]: time="2018-04-14T09:28:36Z" level=fatal msg="read configuration file error" error="While parsing config: (42, 5): keys cannot contain : character"
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: lora-app-server.service: Main process exited, code=exited, status=1/FAILURE
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: lora-app-server.service: Unit entered failed state.
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: lora-app-server.service: Failed with result 'exit-code'.
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: lora-app-server.service: Service hold-off time over, scheduling restart.
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: Stopped LoRa App Server.
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: Started LoRa App Server.
Apr 14 09:28:36 ip-172-31-44-120 lora-app-server[16811]: time="2018-04-14T09:28:36Z" level=fatal msg="read configuration file error" error="While parsing config: (42, 5): keys cannot contain : character"
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: lora-app-server.service: Main process exited, code=exited, status=1/FAILURE
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: lora-app-server.service: Unit entered failed state.
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: lora-app-server.service: Failed with result 'exit-code'.
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: lora-app-server.service: Service hold-off time over, scheduling restart.
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: Stopped LoRa App Server.
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: Started LoRa App Server.
Apr 14 09:28:36 ip-172-31-44-120 lora-app-server[16818]: time="2018-04-14T09:28:36Z" level=fatal msg="read configuration file error" error="While parsing config: (42, 5): keys cannot contain : character"
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: lora-app-server.service: Main process exited, code=exited, status=1/FAILURE
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: lora-app-server.service: Unit entered failed state.
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: lora-app-server.service: Failed with result 'exit-code'.
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: lora-app-server.service: Service hold-off time over, scheduling restart.
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: Stopped LoRa App Server.
Apr 14 09:28:36 ip-172-31-44-120 systemd[1]: lora-app-server.service: Start request repeated too quickly.
Thanks for help :)

**Comment by brocaar** [comment]
> Apr 14 09:28:36 ip-172-31-44-120 lora-app-server[16818]: time="2018-04-14T09:28:36Z" level=fatal msg="read configuration file error" error="While parsing config: (42, 5): keys cannot contain : character"
