### ISSUE TITLE
use docker to run v0.8.0, connect MQTT broker timeout

### ISSUE THREAD

**Issue by ksuie** [brocaar/loraserver#32]
`$ ./loraserver --db-automigrate --net-id 010203 --band EU_863_870 --postgres-dsn "postgres://dbuser:dbpwd@192.168.10.11/loraserver?sslmode=disable" --redis-url "redis://192.168.10.11:6379" --gw-mqtt-server "tcp://test.mosquitto.org:1883" --app-mqtt-server "tcp://test.mosquitto.org:1883"`
INFO[0000] starting LoRa Server                          band=EU_863_870 net_id=010203 version=0.8.0
INFO[0000] connecting to postgresql
INFO[0000] setup redis connection pool
INFO[0000] gateway/mqttpubsub: connecting to mqtt broker  server=tcp://test.mosquitto.org:1883
INFO[0000] application/mqttpubsub: connecting to mqtt broker  server=tcp://test.mosquitto.org:1883
INFO[0000] gateway/mqttpubsub: connected to mqtt server
INFO[0000] gateway/mqttpubsub: subscribing to rx topic   topic=gateway/+/rx
INFO[0001] controller/mqttpubsub: connecting to mqtt broker  server=tcp://localhost:1883
INFO[0001] application/mqttpubsub: connected to mqtt server
INFO[0001] application/mqttpubsub: subscribing to tx topic  topic=application/+/node/+/tx
INFO[0001] applying database migrations
INFO[0001] controller/mqttpubsub: connected to mqtt broker
INFO[0001] controller/mqttpubsub: subscribing to tx topic  topic=application/+/node/+/mac/tx
INFO[0001] migrations applied                            count=0
INFO[0001] registering json-rpc handler                  path=/rpc
INFO[0001] registering gui handler                       path=/
INFO[0001] starting http server                          bind=0.0.0.0:8000

when I use docker to run v0.8.0, i/o timeout. v0.7.0 is ok
`$ docker run --rm -p 8000:8000 loraserver:0.8.0 loraserver --db-automigrate --net-id 010203 --band EU_863_870 --postgres-dsn "postgres://dbuser:dbpwd@192.168.10.11/loraserver?sslmode=disable" --redis-url "redis://192.168.10.11:6379" --gw-mqtt-server "tcp://test.mosquitto.org:1883" --app-mqtt-server "tcp://test.mosquitto.org:1883"`
time="2016-07-04T00:26:07Z" level=info msg="starting LoRa Server" band="EU_863_870" net_id=010203 version=
time="2016-07-04T00:26:07Z" level=info msg="connecting to postgresql"
time="2016-07-04T00:26:07Z" level=info msg="setup redis connection pool"
time="2016-07-04T00:26:07Z" level=info msg="gateway/mqttpubsub: connecting to mqtt broker" server="tcp://test.mosquitto.org:1883"
time="2016-07-04T00:26:22Z" level=fatal msg="gateway-backend setup failed: gateway/mqttpubsub: connecting to broker failed: Network Error : dial tcp 85.119.83.194:1883: i/o timeout"

`$ docker -v`
Docker version 1.11.2, build b9f10c9

**Comment by brocaar** [comment]
I'm not sure how this is related to LoRa Server if it works without Docker. Might as well be a Docker network related issue. Out of curiosity I tried to reproduce your issue, but works like a charm here:

```
docker-compose run --rm loraserver bash
```
```
root@3dd9721cf9be:/go/src/github.com/brocaar/loraserver# loraserver --db-automigrate --net-id 010203 --band EU_863_870 --gw-mqtt-server "tcp://test.mosquitto.org:1883" --app-mqtt-server "tcp://test.mosquitto.org:1883" --controller-mqtt-server "tcp://test.mosquitto.org:1883"
INFO[0000] starting LoRa Server                          band=EU_863_870 net_id=010203 version=0.8.0-5-geb998f7
INFO[0000] connecting to postgresql
INFO[0000] setup redis connection pool
INFO[0000] gateway/mqttpubsub: connecting to mqtt broker  server=tcp://test.mosquitto.org:1883
INFO[0000] application/mqttpubsub: connecting to mqtt broker  server=tcp://test.mosquitto.org:1883
INFO[0000] gateway/mqttpubsub: connected to mqtt server
INFO[0000] gateway/mqttpubsub: subscribing to rx topic   topic=gateway/+/rx
INFO[0000] controller/mqttpubsub: connecting to mqtt broker  server=tcp://test.mosquitto.org:1883
INFO[0000] application/mqttpubsub: connected to mqtt server
INFO[0000] application/mqttpubsub: subscribing to tx topic  topic=application/+/node/+/tx
INFO[0000] applying database migrations
INFO[0000] controller/mqttpubsub: connected to mqtt broker
INFO[0000] controller/mqttpubsub: subscribing to tx topic  topic=application/+/node/+/mac/tx
INFO[0000] migrations applied                            count=2
INFO[0000] registering json-rpc handler                  path=/rpc
INFO[0000] registering gui handler                       path=/
INFO[0000] starting http server                          bind=0.0.0.0:8000
```

Btw, don't forget to pass the ``--controller-mqtt-server``.
