### ISSUE TITLE
node join-request (OTTA) failed

### ISSUE THREAD

**Issue by Vast-Stars** [brocaar/loraserver#325]
I installed all momponents by following https://www.loraserver.io/install/quick-install/ and setup in Lora App Server WebUI interface (including nodes' DevEUI、AppKey)  . **I can see Gateway activity but my nodes can not join in.** 
type `mosquitto_sub -t "gateway/#" -u loraroot -P {XXXXXX} -v` I can see Gateway stats package once a minute. After I start the power of nodes, Ican see join-request like:

>  gateway/0002e4956e4bb547/rx {"rxInfo":{"mac":"0002e4956e4bb547","time":"2018-05-21T14:11:24.408761Z","timeSinceGPSEpoch":"336374h11m43.408s","timestamp":1961806796,"frequency":481500000,"channel":0,"rfChain":0,"crcStatus":1,"codeRate":"4/5","rssi":-65,"loRaSNR":7,"size":23,"dataRate":{"modulation":"LORA","spreadFactor":9,"bandwidth":125},"board":0,"antenna":0},"phyPayload":"AAEAAAAAAAAA////EAAAEBNdRWs6u14="}

> gateway/0002e4956e4bb547/rx {"rxInfo":{"mac":"0002e4956e4bb547","time":"2018-05-21T14:11:31.458314Z","timeSinceGPSEpoch":"336374h11m50.457s","timestamp":1968856340,"frequency":481900000,"channel":2,"rfChain":0,"crcStatus":1,"codeRate":"4/5","rssi":-63,"loRaSNR":8,"size":23,"dataRate":{"modulation":"LORA","spreadFactor":9,"bandwidth":125},"board":0,"antenna":0},"phyPayload":"AAEAAAAAAAAA////EAAAEBPBdC3K/ZI="}

So what's wrong with my configurations ? Is that because I run `sudo systemctl start loraserver` or something simply ?

**Comment by brocaar** [comment]
Please see: https://forum.loraserver.io/t/node-activation-otaa-issues/474.
