### ISSUE TITLE
processing rx packet error: get device-session error

### ISSUE THREAD

**Issue by lemonbuzz** [brocaar/loraserver#332]
### Is this a bug or a feature request?
More like requesting some help
### What did you expect?
Not getting this error
### What happened?
level=error msg="processing rx packet error: get device-session error: device-session does not exist or invalid fcnt or mic" data_base64=QHhWNBKAjQCXn+5GGRqxl
### What version are your using?
0.26.1

Hi, I am relatively new to LoRa and I need some help to get my setup running, I am sorry if this is the wrong place. Now, before you close my issue and direct me where this has already been answered, let me tell you that I have read those threads and they did not help.

Join Method: ABP

I have created a device in the lora-app, took the generated device address, NetworkSK, AppSK and put that configuration in my test node.

When I send a packet from the node, I can see loraserver receiving it from the gateway-bridge but it seems like it cannot process/decode/decrypt it for some reason.

What I have tried(because the error message mentioned something about the frame counter being out of sync with the node) was to create a new node and disable the frame counter. This didn't change much and loraserver still emits the same error.

Help is very appreciated :).

( I have also looked into the byte order of the addresses )

**Comment by brocaar** [comment]
For support questions see https://forum.loraserver.io
