### ISSUE TITLE
MQTT QOS Level setting

### ISSUE THREAD

**Issue by M4riko** [brocaar/loraserver#343]
I have tried to change the QOS level to 1 and 2 in all 3 loraserver applications on my server. But still all the messages are sent with QOS level0. Is this a known problem? or am i doing something wrong?

**Comment by brocaar** [comment]
The QOS set in `loraserver.toml` applies to the message published to the MQTT broker (in the direction of the gateway).

**Comment by brocaar** [comment]
Probably this issue was caused by https://github.com/brocaar/lora-gateway-bridge/pull/95.
