### ISSUE TITLE
MongoDB and MySql Integration!

### ISSUE THREAD

**Issue by tusharvb19** [brocaar/loraserver#348]
### feature request
Integration for MongoDB and MySql?
Also is the uplink data is directly inserted into the database?

**Comment by brocaar** [comment]
This won't be supported but please note that LoRa App Server supports sending data over:

* GCP Pub/Sub
* MQTT
* HTTP
* InfluxDB

Using the Pub/Sub, MQTT or HTTP integration one could easily write an application to write the data to a database of choice :-)
