### ISSUE TITLE
 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sleepingAnt** [brocaar/loraserver#349]
Hi, every time I received rx packet, I get errors below, and loraserver crashed.

```
INFO[0103] backend/gateway: rx packet received
INFO[0103] creating application-server client            server="localhost:8001"
INFO[0103] rx info sent to network-controller            dev_eui=401f000010ffffff
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xa19886]

goroutine 285 [running]:
github.com/brocaar/loraserver/internal/uplink/data.sendFRMPayloadToApplicationServer.func1(0x0, 0x0, 0xc4200c09cc, 0x8, 0x8, 0xc4200c09d4, 0x8, 0x8, 0x2100000010, 0x500000001, ...)
        /home/travis/gopath/src/github.com/brocaar/loraserver/internal/uplink/data/data.go:403 +0xc6
created by github.com/brocaar/loraserver/internal/uplink/data.sendFRMPayloadToApplicationServer
        /home/travis/gopath/src/github.com/brocaar/loraserver/internal/uplink/data/data.go:398 +0x815
```

**Comment by brocaar** [comment]
* Which version are you using?
* Did you make any modifications?

**Comment by brocaar** [comment]
I tried to reproduce your issue, but I'm unable to.... are you still experiencing this issue / do you have more hints how I can reproduce it?

**Comment by sleepingAnt** [comment]
When I leave `"Network-servers -> TLS Certificates" in the lora-app-server web page` empty, everything is ok.
I think this is caused by that I didn't set TLS Certificates in `loraserver` config file, but used tls in the lora-app-server web page.

**Comment by brocaar** [comment]
Hmm interesting. I would expect that you would get an error. Will test with that again. Please keep this issue open.

When you don't set any certificates in `loraserver.toml` and `lora-app-server.toml`, you should not enter any certificate information in LoRa App Server when adding the network-server.

**Comment by sleepingAnt** [comment]
Okay, thanks man!

**Comment by brocaar** [comment]
I'm able now to reproduce the issue. It happens when the CA certificate is blank, but the TLS cert and key are populated.
