### ISSUE TITLE
Different GPS modules families for class-b downlink

### ISSUE THREAD

**Issue by andrewrene** [brocaar/loraserver#350]
Hi Brocaar, 
Can I use another GNSS module to successfully verify class-b downlink flow except the u-blox7 ? or what should I do to successfully send a class-b downlink packet from forwarder side with another GNSS module? Appreciate any suggestions on this.

**Comment by brocaar** [comment]
This is not a LoRa Server restriction. the GPS module needs to be supported by the packet-forwarder. https://github.com/lora-net/packet_forwarder is a better place to drop your question.
