### ISSUE TITLE
Too many records in messages log file.

### ISSUE THREAD

**Issue by Vini74** [brocaar/loraserver#356]
Latest server. CentOS7
file /var/log/messages
Is it possibe to turn off this messages?
log_level parameter does not work in this situation.

Oct  1 12:14:33 loraserver mosquitto: 1538385273: |-- aclcheck(loraserver_gw, gateway/0000985dad86e52f/stats, 2) CACHEDAUTH: 0
Oct  1 12:14:33 loraserver mosquitto: 1538385273: |-- mosquitto_auth_acl_check(..., b13f5409-cdd1-4f11-a3cc-e765e41741c7, loraserver
_ns, gateway/0000985dad86e52f/stats, MOSQ_ACL_READ)
Oct  1 12:14:33 loraserver mosquitto: 1538385273: |-- aclcheck(loraserver_ns, gateway/0000985dad86e52f/stats, 1) CACHEDAUTH: 0
Oct  1 12:15:03 loraserver mosquitto: 1538385303: |-- mosquitto_auth_acl_check(..., a1c894d6-4445-4003-89a9-950821744ca0, loraserver
_gw, gateway/0000985dad86e52f/stats, MOSQ_ACL_WRITE)
Oct  1 12:15:03 loraserver mosquitto: 1538385303: |-- aclcheck(loraserver_gw, gateway/0000985dad86e52f/stats, 2) CACHEDAUTH: 0
Oct  1 12:15:03 loraserver mosquitto: 1538385303: |-- mosquitto_auth_acl_check(..., b13f5409-cdd1-4f11-a3cc-e765e41741c7, loraserver
_ns, gateway/0000985dad86e52f/stats, MOSQ_ACL_READ)
Oct  1 12:15:03 loraserver mosquitto: 1538385303: |-- aclcheck(loraserver_ns, gateway/0000985dad86e52f/stats, 1) CACHEDAUTH: 0
Oct  1 12:15:33 loraserver mosquitto: 1538385333: |-- mosquitto_auth_acl_check(..., a1c894d6-4445-4003-89a9-950821744ca0, loraserver
_gw, gateway/0000985dad86e52f/stats, MOSQ_ACL_WRITE)
Oct  1 12:15:33 loraserver mosquitto: 1538385333: |-- aclcheck(loraserver_gw, gateway/0000985dad86e52f/stats, 2) CACHEDAUTH: 0
Oct  1 12:15:33 loraserver mosquitto: 1538385333: |-- mosquitto_auth_acl_check(..., b13f5409-cdd1-4f11-a3cc-e765e41741c7, loraserver
_ns, gateway/0000985dad86e52f/stats, MOSQ_ACL_READ)
Oct  1 12:15:33 loraserver mosquitto: 1538385333: |-- aclcheck(loraserver_ns, gateway/0000985dad86e52f/stats, 1) CACHEDAUTH: 0
Oct  1 12:16:03 loraserver mosquitto: 1538385363: |-- mosquitto_auth_acl_check(..., a1c894d6-4445-4003-89a9-950821744ca0, loraserver
_gw, gateway/0000985dad86e52f/stats, MOSQ_ACL_WRITE)
Oct  1 12:16:03 loraserver mosquitto: 1538385363: |-- aclcheck(loraserver_gw, gateway/0000985dad86e52f/stats, 2) CACHEDAUTH: 0
Oct  1 12:16:03 loraserver mosquitto: 1538385363: |-- mosquitto_auth_acl_check(..., b13f5409-cdd1-4f11-a3cc-e765e41741c7, loraserver
_ns, gateway/0000985dad86e52f/stats, MOSQ_ACL_READ)
Oct  1 12:16:03 loraserver mosquitto: 1538385363: |-- aclcheck(loraserver_ns, gateway/0000985dad86e52f/stats, 1) CACHEDAUTH: 0
Oct  1 12:16:33 loraserver mosquitto: 1538385393: |-- mosquitto_auth_acl_check(..., a1c894d6-4445-4003-89a9-950821744ca0, loraserver
_gw, gateway/0000985dad86e52f/stats, MOSQ_ACL_WRITE)
Oct  1 12:16:33 loraserver mosquitto: 1538385393: |-- aclcheck(loraserver_gw, gateway/0000985dad86e52f/stats, 2) CACHEDAUTH: 0
Oct  1 12:16:33 loraserver mosquitto: 1538385393: |-- mosquitto_auth_acl_check(..., b13f5409-cdd1-4f11-a3cc-e765e41741c7, loraserver
_ns, gateway/0000985dad86e52f/stats, MOSQ_ACL_READ)
Oct  1 12:16:33 loraserver mosquitto: 1538385393: |-- aclcheck(loraserver_ns, gateway/0000985dad86e52f/stats, 1) CACHEDAUTH: 0
Oct  1 12:16:50 loraserver mosquitto: 1538385410: |-- mosquitto_auth_acl_check(..., a1c894d6-4445-4003-89a9-950821744ca0, loraserver
_gw, gateway/0000985dad86e52f/rx, MOSQ_ACL_WRITE)
Oct  1 12:16:50 loraserver mosquitto: 1538385410: |-- aclcheck(loraserver_gw, gateway/0000985dad86e52f/rx, 2) CACHEDAUTH: 0
Oct  1 12:16:50 loraserver mosquitto: 1538385410: |-- mosquitto_auth_acl_check(..., b13f5409-cdd1-4f11-a3cc-e765e41741c7, loraserver
_ns, gateway/0000985dad86e52f/rx, MOSQ_ACL_READ)
Oct  1 12:16:50 loraserver mosquitto: 1538385410: |-- aclcheck(loraserver_ns, gateway/0000985dad86e52f/rx, 1) CACHEDAUTH: 0
Oct  1 12:16:50 loraserver mosquitto: 1538385410: |-- mosquitto_auth_acl_check(..., 385b9ce6-d548-4c9a-97e4-6486faa2cd0c, loraserver
_as, application/2/device/3331383274358905/rx, MOSQ_ACL_WRITE)
Oct  1 12:16:50 loraserver mosquitto: 1538385410: |--  Expired [A0E0ED68BF81E3ED658C969DB63CD5DDFBD8B028] for (385b9ce6-d548-4c9a-97
e4-6486faa2cd0c,loraserver_as,2)

**Comment by brocaar** [comment]
These are mosquitto logs. Please check your mosquitto configuration.

**Comment by Vini74** [comment]
Oh. Yes... loraserver is a hostname.
Problem solved by adding "auth_opt_log_quiet true" in mosquitto auth_plugin config.
For your information.
