### ISSUE TITLE
Diversity GW, Loraserver doesn't use correct rfchain

### ISSUE THREAD

**Issue by mlandinger** [brocaar/loraserver#363]
### Is this a bug!
Who should make the decision for the better path in case of diversity reception?

I see the PF is forwarding both rfchains to the lora-gateway-bridge:
[1544185143]
INFO: Received pkt from mote: 007B26A5 (fcnt=12131)
[1544185143]
INFO: Received pkt from mote: 007B26A5 (fcnt=12131)
[1544185143]
JSON up: {“rxpk”:[{“tmst”:8414051,“chan”:2,“rfch”:0,“freq”:868.500000,“stat”:1,“modu”:“LORA”,“datr”:“SF7BW125”,“codr”:“4/5”,“lsnr”:-5.8,“rssi”:-125,“size”:29,“data”:“QKUmewCAYy8F1Ku8noi8wC06QHwlGOH2PlhAdCg=”},{“tmst”:8414051,“chan”:22,“rfch”:1,“freq”:868.500000,“stat”:1,“modu”:“LORA”,“datr”:“SF7BW125”,“codr”:“4/5”,“lsnr”:10.2,“rssi”:-108,“size”:29,“data”:“QKUmewCAYy8F1Ku8noi8wC06QHwlGOH2PlhAdCg=”}]}
[1544185143] INFO: [up] PUSH_ACK received in 7 ms

The “lora-gateway-bridge” is publishing both rxpk:
gateway/647fdafffe005249/rx {“rxInfo”:{“mac”:“647fdafffe005249”,“timestamp”:8414051,“frequency”:868500000,“channel”:2,“rfChain”:0,“crcStatus”:1,“codeRate”:“4/5”,“rssi”:-125,“loRaSNR”:-5.8,“size”:29,“dataRate”:{“modulation”:“LORA”,“spreadFactor”:7,“bandwidth”:125},“board”:0,“antenna”:0},“phyPayload”:“QKUmewCAYy8F1Ku8noi8wC06QHwlGOH2PlhAdCg=”}
gateway/647fdafffe005249/rx {“rxInfo”:{“mac”:“647fdafffe005249”,“timestamp”:8414051,“frequency”:868500000,“channel”:22,“rfChain”:1,“crcStatus”:1,“codeRate”:“4/5”,“rssi”:-108,“loRaSNR”:10.2,“size”:29,“dataRate”:{“modulation”:“LORA”,“spreadFactor”:7,“bandwidth”:125},“board”:0,“antenna”:0},“phyPayload”:“QKUmewCAYy8F1Ku8noi8wC06QHwlGOH2PlhAdCg=”}

**But the “loraserver” uses the first one which is the worse one (rfChain:0)!!**

**Comment by brocaar** [comment]
Closing this issue as a fix is proposed in https://github.com/brocaar/loraserver/issues/401.
