### ISSUE TITLE
downlink message sent without delay

### ISSUE THREAD

**Issue by wireless-road** [brocaar/loraserver#365]
Hi!
I've downloaded and installed `Loraserver` + `lora-app-server` 6 month ago and was able to launch it out of box. But I have problem with new version:  `Loraserver` sends `Join accept` packet immediately so Lorawan node not able to detect it as I assume it expects a delay between Uplink and downlink message. Not even sure if there is a problem with loraserver or with `packet-forwarder` (fresh new version 4.0.1). TTN handle Join request and sends responce after 5 sec delay and end node able to receive Join accept.
Some info can be found here:
https://forum.loraserver.io/t/end-node-doesnt-see-lora-app-servers-join-response/2883/3
Here I got advice to edit some config parameter but not sure that this is proper way. As I understand delay between uplink and downlink message should be implemented out of box as it was with older version of loraserver.
What is the proper way of handling delays between uplink and downlink messages as it it required for lorawan protocol?

**Comment by brocaar** [comment]
Looking at the linked topic, it seems the issue has been resolved and was caused by a mis-configured LoRaWAN version (1.0 vs 1.1).
