### ISSUE TITLE
LoraServer does not persist seassions

### ISSUE THREAD

**Issue by alex00971** [brocaar/loraserver#366]
Hi

Lora node connected by OTAA , Everything goes well.

I restart the LoraServer (lora app server,bridge,redis server,mqtt server)

Device is not recognized any more, until I restart the device.

Versions : AppServer 2.4 , Gateway bridge 2.6.1 , loraserver 2.3.

to reproduce the issue : 
Connect a node, restart servers.
![image](https://user-images.githubusercontent.com/9721014/50399236-63f57e80-0797-11e9-8efb-dd6247139d19.png)

Now when I check the log, it seems LoraServer does not persist sessions.

**Comment by brocaar** [comment]
This is not a bug. This is either related to the device-session TTL configuration in `loraserver.toml` or your Redis configuration.
