### ISSUE TITLE
Crash on Rejoin1

### ISSUE THREAD

**Issue by jamesl-dm** [brocaar/loraserver#367]
Hi Orne,

I just tried out a Rejoin1 request, and it looks like it crashes the server.

### Is this a bug or a feature request?
Looks like a bug. Entirely possible I'm sending it a corrupt request, but I still wouldn't expect a crash.

### What did you expect?
Either no response, or a join accept.

### What happened?
The server dumped core after receiving the packet.

### What version are your using?
2.4.1 Ubuntu binaries

### How can your issue be reproduced?
I configured an OTAA 1.1 device on AS923, and had it sent a rejoin1 request after the initial join and configuration downlinks had been exchanged.

### Could you share your log output?
[rejoin1 crash.txt](https://github.com/brocaar/loraserver/files/2785784/rejoin1.crash.txt)

**Comment by brocaar** [comment]
Thanks for reporting. I have found the issue 👍

**Comment by brocaar** [comment]
Rejoin 1 has not been implemented yet as at the time of implementing the rejoin, I was unable to test this. The fix shows an error instead of panicing. I will try to implement rejoin type 1 soon. Thanks again for reporting.
