### ISSUE TITLE
docker-compose up

### ISSUE THREAD

**Issue by wshaw2006** [brocaar/loraserver#368]
docker-compose up
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by brocaar** [comment]
I think this issue has to do with your Docker setup, not with LoRa Server. See also: https://www.google.com/search?client=firefox-b-ab&q=Couldn%27t+connect+to+Docker+daemon+at+http%2Bdocker%3A%2F%2Flocalhost+-+is+it+running%3F.
