### ISSUE TITLE
ADR

### ISSUE THREAD

**Issue by gq-tang** [brocaar/loraserver#372]
### Is this a bug or a feature request?
bug
### What happened?
The server also issues the LinkADRReq command when the terminal is not set to ADR.
### What version are your using?
loraserver v2.3.0
### Could you share your log output?
![screenshot from 2019-02-15 15-01-44](https://user-images.githubusercontent.com/21092296/52840059-119b6300-3133-11e9-8729-b2f3081b4031.png)
![downlink](https://user-images.githubusercontent.com/21092296/52840060-1233f980-3133-11e9-8773-c6bace87c384.png)

**Comment by brocaar** [comment]
This is not a bug. The LinkADRReq is also used to send new channel-masks to the device.
