### ISSUE TITLE
loraserver don't send fre config

### ISSUE THREAD

**Issue by alexbondarchuk** [brocaar/loraserver#373]
### Is this a bug or a feature request?
bug
### What happened?
loraserver don't send fre config to gateways
### What version are your using?
2.4.0, 2.4.1, 2.5.0
### Could you share your log output?
https://forum.loraserver.io/t/mqtt-topic-for-gateway-config-not-updated/3205/6

**Comment by brocaar** [comment]
Sorry for the inconveniece. It looks like the line which triggered the config update got removed during a refactor / merge / rebase. The above commit fixes this.

**Comment by alexbondarchuk** [comment]
thanks!
