### ISSUE TITLE
Missing crcStatus in JSON Uplink Frames

### ISSUE THREAD

**Issue by stevenhaslam** [brocaar/loraserver#381]
### Is this a bug or a feature request?
Potential bug or a change in the design that does not appear to have been articulated in the documentation.  

### What did you expect?
We are in the procress of building parallel support for V2 JSON (currently in use) and the newer JSON structure.  In the V2 JSON gateway bridge uplink frames included the crcStatus field to indicate whether the frame passed CRC (1), failed (-1) or no CRC check was performed (0).  Various different LoRa gateways support sending this CRC information and this is often configurable in the packet forwarder.

### What happened?
In the new JSON structure we are no seeing the crcStatus field and thus are wondering if this is bug or the bridge software is filtering out failures hence removing the need for the crcStatus.

### What version are your using?
This is being tested with lora server 2.3.0, lora-app-server 2.3.0, gateway bridge 2.6.0 and geo server 2.0.0.  Are initial test was performed using a Tektelic Pico gateway that only forwards CRC successes but we will be testing with MultiTech conduit and Tektelic Macro gateways too that can forward CRC failures.

### How can your issue be reproduced?
Easily, first configure the gateway bridge to send V2 JSON messages and not the crcStatus is present in uplink frames from the gateway.  Then change the bridge setting to JSON and note the incoming json frames no longer include the crcStatus field.

### Could you share your log output?
We can if needed but the lora sever documentation online also shows the crcStatus is missing for JSON uplink frames (https://www.loraserver.io/lora-gateway-bridge/integrate/payload-types/json/) versus V2 JSON uplink frames (https://www.loraserver.io/lora-gateway-bridge/integrate/payload-types/v2-json/).  We are just seeking clarification why the crcstatus is now omitted.

**Comment by brocaar** [comment]
The setting was there, but was indeed not enforced in the latest version. The above commit fixes this.
