### ISSUE TITLE
LoRa redis server error

### ISSUE THREAD

**Issue by sarju32** [brocaar/loraserver#382]
Hi,

Attached is issue faced in LoRa.

Issue is not observed when everything in the Database is removed and added again.
After this when board reboots without deleting the database this issue is obtained.

Thanks & Regards,
Sarjoon

**Comment by brocaar** [comment]
Attachment is missing.

**Comment by sarju32** [comment]
Hi Orne Brocaar,

We tried to attach the image in Bug or Feature request page. Its not 
working,

So we attach the image along with this mail.

Thanks,

-- 

Regards,
Mohamed Sarjoondeen K M
mail: sarjoondeen@iwavesystems.com
iWave Systems Technologies Pvt. Ltd.
http://www.iwavesystems.com/

**Comment by sarju32** [comment]
![redis_error](https://user-images.githubusercontent.com/30067713/54528543-51a86c80-49a3-11e9-8a7f-e3ab2eb8f4a6.png)

**Comment by brocaar** [comment]
This is not a bug. It looks like your (Redis) database is not started on a re-boot and thus LoRa Server complains that it can't connect.
