### ISSUE TITLE
At OTAA, LoRa Server returns Unconffrimed data down to Confirmed data.

### ISSUE THREAD

**Issue by sarju32** [brocaar/loraserver#384]
#Bug
When LoRa node sends unconfirmed data no reply is sent from server immediately, but after sending confirmed data from LoRa node LoRa server sends unconfirmed data.

**Comment by brocaar** [comment]
Which looks valid to me as LoRa Server needs to acknowledge the confirmed uplink.

**Comment by sarju32** [comment]
Please refer below attached LoRa_sequence.png ..
![LoRa_sequence](https://user-images.githubusercontent.com/30067713/54528994-a00a3b00-49a4-11e9-90ed-218ab6ad85c3.png)

The sequence diagram is given, For ConfirmedUp we are not receiving ConfirmedDown Data rather we are seeing UnconfirmedDown. 
Any reason for the attached Is there some delay 

Attached the images that was taken on LoRaWAN packet decoder for each sequence.
![unconfirmed_down](https://user-images.githubusercontent.com/30067713/54529010-b0bab100-49a4-11e9-8294-7d487cf972dc.png)
![unconfirmed_up](https://user-images.githubusercontent.com/30067713/54529012-b0bab100-49a4-11e9-86cd-e3fd03d3beab.png)
![join_accept](https://user-images.githubusercontent.com/30067713/54529013-b0bab100-49a4-11e9-81a4-71f0cd9c3c85.png)
![join_request](https://user-images.githubusercontent.com/30067713/54529014-b1534780-49a4-11e9-95c0-1a19b26290ad.png)
![Uploading confirmed.png…]()
![Uploading confirmed_up.png…]()
