### ISSUE TITLE
Deduplication delay is ignored

### ISSUE THREAD

**Issue by tomasol** [brocaar/loraserver#387]
### Is this a bug or a feature request?
bug
### What did you expect?
Setting 
```
[network_server]
deduplication_delay="300ms"
```
should delay processing of uplinks accordingly.
### What happened?
No delay observed, deduplication does not work properly - uplink contains only one gateway, even though more mqtt messages are observed in /gateway/+/rx per 1 uplink.

### What version are your using?
2.5.0, 2.6.0
### How can your issue be reproduced?
By setting the config value above
### Could you share your log output?
Adding a log message to collect.go reveals:
```
"Sleeping time" deduplicationDelay=0s deduplicationTTL=200ms
```
Looks like uplink.Setup is not called at all in root_run.go
### Fix
Add `uplink.Setup(config.C)` to root_run.go

**Comment by brocaar** [comment]
Good catch :+1:  and embarrassing this issue slipped through during the configuration refactor :-/ .... Will fix asap and issue a new release.
