### ISSUE TITLE
downlink payload exceeds max payload size

### ISSUE THREAD

**Issue by Dimenthy** [brocaar/loraserver#391]
### Is this a bug or a feature request?
bug

### What happened?
When I Send a message  to topic which name is "application/1/device/0065080215000241/tx"
message content like this {"confirmed":true,"fPort":1,"data":"Dw/AAAAAAQgAKAR1AAEAAIWqAB6khQAA7dyYQwAgRVEACMNfAAgZXwAIv18ACGVbAAgddddddd="}
 then I can get a message from the topic which name is  "application/1/device/0065080215000241/error"  
And the message i got like this
{"applicationID":"1","applicationName":"app","deviceName":"0065080215000241","devEUI":"0065080215000241","type":"DEVICE_QUEUE_ITEM_SIZE","error":"payload exceeds max payload size","fCnt":15507}

so , what should i do about this error ? @brocaar 
can u help me?   my English is not very good   ?  Can U understand ? 

CLASS A , ABP

### What version are your using?
loraserver 2.6.1
lora-app-server 2.6.0
lora-gateway-bridge 2.6.1

**Comment by brocaar** [comment]
That is not a bug but a limitation of the LoRaWAN protocol. Please refer to the Region Parameters specification. It contains the max payload size per region and data-rate.

**Comment by Dimenthy** [comment]
Thanks for your reply ！ 
After i comment an issue , I try to change another device and then i downlink success.
