### ISSUE TITLE
Set channel plan per device

### ISSUE THREAD

**Issue by lancepitka** [brocaar/loraserver#392]
### Is this a bug or a feature request?

Feature Request

### What did you expect?

For US 915 networks with some gateways with 8 channels and some with 16 channels, having one channel plan for all devices on the network doesn't work very well. It would be great if we could override the default channel plan for certain devices. That way, the default plan could be to use all 16 channels by default, but override the channel plan to only 8 channels for devices using an 8 channel gateway for example.

**Comment by brocaar** [comment]
I would recommend setting up two LoRa Server instances one for a 8 channel US915 network, an other for a 16 channel US915 network.

Ideally the end-user setting up devices should not be concerned with the network specific settings (like active channels). Giving the end-user the power of selecting which channels to use could cripple your network.

**Comment by lancepitka** [comment]
Setting up two different network servers wouldn't work for my case. I have many devices that move around between 8 and 16 channel gateways. Unless there is a way to setup some sort of roaming between my two network servers, I don't think it would work.

**Comment by brocaar** [comment]
Potentially you could forward all data to a single MQTT broker and let both LoRa Server instances use the uplink data from all 16 ch + 8 ch gateways.

Make sure that each LoRa Server instance has its own Redis and PostgreSQL database. So they share the same gateways, but not the device states.

**Comment by lancepitka** [comment]
That's a good idea. I think that should work. I will give it a try. Thanks!

Is there a way to disable the gateway channel reconfiguration packet on the loraserver? I can ignore it on the gateways, but having that packet sent from each network server uses that much more data. I don't know how much data this actually uses - maybe it is negligible?

**Comment by brocaar** [comment]
Just not assign a gateway profile :-) The only thing it is used for is sending the config to the LoRa Gateway Bridge.

**Comment by lancepitka** [comment]
I didn't realize that! Thanks for the help

**Comment by brocaar** [comment]
Can this issue be closed?

**Comment by lancepitka** [comment]
Yes it can. Thanks!
