### ISSUE TITLE
LoRa Geo Server gRPC api call using C#

### ISSUE THREAD

**Issue by sagar-patel-sls** [brocaar/loraserver#394]
How can we call Ger Server gRPC Api call using C# for geolocation service

Any document related ger-server gRPC api?
or 
how can we get lora node location using Geo-server?

i already test below c# example
[https://github.com/grpc/grpc/tree/master/examples/csharp/Helloworld](https://github.com/grpc/grpc/tree/master/examples/csharp/Helloworld)

Thanks you

**Comment by brocaar** [comment]
This is the .proto file:
https://github.com/brocaar/loraserver/blob/master/api/geo/geo.proto

From this document you need to generate the C# API. See also: https://grpc.io/docs/quickstart/csharp/.
