### ISSUE TITLE
limit the number of redis connections get by lorasever

### ISSUE THREAD

**Issue by orientlu** [brocaar/loraserver#398]
### Is this a bug or a feature request?
i think is a bug

### What did you expect?
i try to fix and  had subminted a pr

### What happened?
when i do a perf test ,i found loraserver print so much error log which say redis connection timeout, and i found loraserver get more than 9990 connection(max is 10000).

**Comment by orientlu** [comment]
and i suggest postgsql should do the limit too， because i encountered the situatioon which as total did not work because ns get too much psql client connections。

**Comment by brocaar** [comment]
:+: This has been fixed. I've updated your pull-request to make this a config option :-)

**Comment by orientlu** [comment]
> :+: This has been fixed. I've updated your pull-request to make this a config option :-)
and postgsql
