### ISSUE TITLE
loraserver ignoring packets from multiple Rx paths

### ISSUE THREAD

**Issue by KarthikSubramanian2** [brocaar/loraserver#401]
### Is this a bug or a feature request?
bug

### What did you expect?
Even though there are multiple packets generated for the same uplink through one gateway, loraserver should dedup them and not lock based on just the first packet.

### What happened?
Since the lock is only on the first packet with the key `lora:ns:uplink:lock:<GatewayID>:<PhyPayload>"`, there is a chance of the original packet with a better signal strength getting dropped which causes a wrong downlink and a bunch of retry packets(which also get dropped with the FC validation enabled causing the sensor to rejoin).

### What version are your using?
2.6.1

### How can your issue be reproduced?
Simulate two Rx packets with the same gateway ID and different RSSIs and different channels. 

### Could you share your log output?
```
"SET" "lora:ns:uplink:lock:0000000000000002:80ab47c80000000001f6a5bedb10214997c409a9cd" "lock" "PX" "500" "NX"
```

**Comment by KarthikSubramanian2** [comment]
If we can add `Channel` as part of the lock key to eliminate the multiple subscription issue, then the duplicate packets due to multiple Rx paths might go to Redis and then the sorting algorithm would pick up the right packet.

**Comment by brocaar** [comment]
How close is your device to the gateway? Usually this happens only when your device is really close.

**Comment by KarthikSubramanian2** [comment]
Thanks for your reply. You are spot on. We have observed this issue in two different scenarios. 
1) As you mentioned, when the device signal strength is too strong (close to the gateway)
2) Also when the gateway is in a highly reflective environment(in our cases with proximity to multiple small metal containers) 

For a small rollout, moving the sensor or gateway would probably solve it. But when we have 100s of sensors and multiple gateways in a constrained space, this issue is really difficult to avoid. 

In those scenarios, it would be great if our software solution handles it and not be concerned about the gateway and sensor proximity. I also like that loraserver is built in a way that the fix should be easy to incorporate as well. 

Curious to hear your thoughts.

**Comment by KarthikSubramanian2** [comment]
@brocaar I can test it out and create a PR if everything looks good.

**Comment by brocaar** [comment]
@KarthikSubramanian2 yes please create a pull-request for this :+1: I think the best way would be to add the Frequency to the key, not the Channel (number). E.g.

```
"SET" "lora:ns:uplink:lock:0000000000000002:868100000:80ab47c80000000001f6a5bedb10214997c409a9cd" "lock" "PX" "500" "NX"
```
