### ISSUE TITLE
Why I modified the static folder(index.html), but after recompile no change?

### ISSUE THREAD

**Issue by yzk0281** [brocaar/loraserver#41]
Why I modified the static folder(index.html), but after recompile no change?
Do I need to use tool 'go-bindata' to regenerate static pkg？

**Comment by yzk0281** [comment]
go-bindata needed~~

**Comment by ivajloip** [comment]
Maybe it will be nice to have this done automatically by make if there is `go-bindata` installed and an informative message otherwise (it took me some time to figure out how exactly to generate the same `static_gen.go`).
