### ISSUE TITLE
How does the field ConfFCnt work during calculating MIC in LoRaWANv1.1?

### ISSUE THREAD

**Issue by carrymybaby** [brocaar/loraserver#411]
### Is this a bug or a feature request?
Maybe feature request
### What happened?
In LoRaWANv1.1 protocol，ConfFCnt is described as the frame counter value modulo 2^16 of the “confirmed” downlink frame when the ACK bit of the uplink frame is set . In source code, I found this line:
 if !qi.Confirmed {...}
    else{ctx.DeviceSession.ConfFCnt = qi.FCnt}                  
In this way, FCnt is a counter for all frames, Is this the right way to decide ConfFCnt?  Maybe ConfFCnt count all confirmed frames and unconfirmed frames?

**Comment by brocaar** [comment]
The `ConfFCnt` **must be equal** to the `FCnt` of the confirmed-uplink which is acknowledged.
