### ISSUE TITLE
Unable to set network_server.gateway.backend.mqtt.password via ENV

### ISSUE THREAD

**Issue by JohnRoesler** [brocaar/loraserver#418]
### Is this a bug or a feature request?
bug?
### What did you expect?
To be able to set the network_server.gateway.backend.mqtt.password via an environment variable similar to other config values
### What happened?
I am able to see the ENV injected in my kubernetes container - however the loraserver receives a bad credentials error from mqtt.

Setting the password directly in the config file works as expected
```
# Connect with the given password (optional)
password="<my password>"
```
### What version are you using?
2.6.1
### How can your issue be reproduced?
Set the environment variable `NETWORK_SERVER.GATEWAY.BACKEND.MQTT.PASSWORD` and connect to an mqtt broker with authentication 
### Could you share your log output?

ENV on container
```
NETWORK_SERVER.GATEWAY.BACKEND.MQTT.PASSWORD=<my password>
```
credential error
```
time="2019-08-13T17:19:31Z" level=error msg="gateway/mqtt: connecting to mqtt broker failed, will retry in 2s: Bad user name or password"
```

**Comment by brocaar** [comment]
Works for me from the cli using the latest master version (fish shell, which is why I needed to add `env` in front of the env variables).

This sets the env. variable and let loraserver print the configuration file. As you can see, it does set the password:

```
~/W/P/L/R/loraserver (master|✔) $ env NETWORK_SERVER.GATEWAY.BACKEND.MQTT.PASSWORD=foobar ./build/loraserver configfile |grep -B 10 -A 10 foobar
```

```
    #   * "{{ .CommandType }}" as an substitution for the command type
    command_topic_template="gateway/{{ .GatewayID }}/command/{{ .CommandType }}"

    # MQTT server (e.g. scheme://host:port where scheme is tcp, ssl or ws)
    server="tcp://localhost:1883"

    # Connect with the given username (optional)
    username=""

    # Connect with the given password (optional)
    password="foobar"

    # Quality of service level
    #
    # 0: at most once
    # 1: at least once
    # 2: exactly once
    #
    # Note: an increase of this value will decrease the performance.
    # For more information: https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels
    qos=0
```
