### ISSUE TITLE
Send CreateMACCommandQueueItem from outside using GRPC Api

### ISSUE THREAD

**Issue by sagar-patel-sls** [brocaar/loraserver#423]
Hii,

we have implemented our custom (Proprietary) MAC command in device binary for configuration of device (e.g DutyCycleReq, Join/AcceptDelay1&2Req) we are trying to send this custom mac command using GRPC API `CreateMACCommandQueueItem`

we have already generated C# API from .proto file
 ```
NetworkServerService.NetworkServerServiceClient networkServerServiceClient = new NetworkServerService.NetworkServerServiceClient(channel);
var devEui = ByteString.CopyFrom("A84041000181B2AA", Encoding.Unicode);
CreateMACCommandQueueItemRequest createMACCommandQueueItemRequest = new CreateMACCommandQueueItemRequest
            {
                Cid = 0x06,
                DevEui = devEui
            };
            createMACCommandQueueItemRequest.MergeFrom(createMACCommandQueueItemRequest);
            var ns = networkServerServiceClient.CreateMACCommandQueueItem(createMACCommandQueueItemRequest);
```
when we send command command successfully in queue of loraserver but we can't received on device side

also can we send mac command through MQTT --> Reference   [https://github.com/brocaar/loraserver/issues/80](https://github.com/brocaar/loraserver/issues/80)

Anyone can help us

Thanks

**Comment by brocaar** [comment]
I'm closing this issue as this has already been posted on the forum which is a better place for community support.
