### ISSUE TITLE
One device and two Dev_EUI

### ISSUE THREAD

**Issue by Helis17** [brocaar/loraserver#424]
Hi.
I have a device registration problem.
Manufacturer sent keys for ABP and OTAA.
On their server, with these keys, the device works fine, it does not work on the lover server.
I registered both ABP and OTAA, it doesn’t work
When I enter Dev_EUI when registering, in the server logs it gives out another maiden with this dev_adr. If I enter that maiden eui, which is issued in the logs, then in the logs it gives another dev_EUI. And in the server logs issued two different dev_EUI with one Dev_Addr
A very strange situation. In the screenshots I put everything
Frame counter disabled
<a href="http://www.picshare.ru/view/10248868/" target="_blank"><img src="http://www.picshare.ru/uploads/190827/CHaZ6TO0jR_thumb.jpg" border="0" title="Хостинг картинок PicShare.ru"></a> <a href="http://www.picshare.ru/view/10248869/" target="_blank"><img src="http://www.picshare.ru/uploads/190827/LExOf13Bie_thumb.jpg" border="0" title="Хостинг картинок PicShare.ru"></a> <a href="http://www.picshare.ru/view/10248870/" target="_blank"><img src="http://www.picshare.ru/uploads/190827/qKodyKhevW_thumb.jpg" border="0" title="Хостинг картинок PicShare.ru"></a> <a href="http://www.picshare.ru/view/10248871/" target="_blank"><img src="http://www.picshare.ru/uploads/190827/mt8lQe1Qz1_thumb.jpg" border="0" title="Хостинг картинок PicShare.ru"></a> <a href="http://www.picshare.ru/view/10248872/" target="_blank"><img src="http://www.picshare.ru/uploads/190827/1R68ha0575_thumb.jpg" border="0" title="Хостинг картинок PicShare.ru"></a> <a href="http://www.picshare.ru/view/10248873/" target="_blank"><img src="http://www.picshare.ru/uploads/190827/sqYxl6ALzr_thumb.jpg" border="0" title="Хостинг картинок PicShare.ru"></a>

**Comment by brocaar** [comment]
For community support, please use the forum: https://forum.loraserver.io. You will find already some topics related to ABP and OTAA activation issues, so I recommend to use the search first.
