### ISSUE TITLE
Time synchronize and batch upload

### ISSUE THREAD

**Issue by mttbx** [brocaar/loraserver#430]
I want to know if there's some methods to synchronize my device time (know the real world time) . And I also want to know if there's some methods to batch the messages before upload(to release the pressure of cloud). If there's no such methods, can you give me some advice?
I'm newbee of lora, can you help me?

**Comment by mttbx** [comment]
Any help would be graceful

**Comment by brocaar** [comment]
Yes, you can use the `DeviceTimeReq` mac-command for this (initiated from the device). Please refer the LoRaWAN specification for more details on this. For batch uploading, you can use the gRPC or REST api.

Next time, please use the forum: https://forum.loraserver.io, it is a better place for general questions. GitHub is better for bugreporting or feature requests.
