### ISSUE TITLE
Loraserver on RAK 2245 PiHut - Device data once and then nothing

### ISSUE THREAD

**Issue by tamasbankuti** [brocaar/loraserver#431]
Hello, 

I am having issues with my loraserver as it receives only one device data packet in the gui and it stops receiving any others.. but the lorawan frames are coming in every 4-5 seconds. Not sure what is happening. It was working OK on TTN but decided to use loraserver.

**Comment by brocaar** [comment]
It might be better to post your question in the forum: https://forum.loraserver.io as I'm not sure if this is an issue with your gateway, device, configuration or an actual bug in LoRa Server.
