### ISSUE TITLE
Compile code failed，undefined: migrations.Asset

### ISSUE THREAD

**Issue by lydit** [brocaar/loraserver#441]
When I compiled the project through go, I was prompted with a failure. The compiler runs in win10*64. The compilation command is as follows
C:\Users\lydit\Desktop\loraserver-master\cmd\loraserver>SET CGO_ENABLED=0
C:\Users\lydit\Desktop\loraserver-master\cmd\loraserver>SET GOOS=linux
C:\Users\lydit\Desktop\loraserver-master\cmd\loraserver>SET GOARCH=arm
C:\Users\lydit\Desktop\loraserver-master\cmd\loraserver>SET GOARM=7
C:\Users\lydit\Desktop\loraserver-master\cmd\loraserver>go build main.go
Error prompts are as follows

github.com/brocaar/loraserver/internal/storage
…\internal\storage\storage.go:81:14: undefined: migrations.Asset
…\internal\storage\storage.go:82:14: undefined: migrations.AssetDir
thanks

**Comment by brocaar** [comment]
Please see https://www.loraserver.io/loraserver/community/source/.
