### ISSUE TITLE
Time of message send

### ISSUE THREAD

**Issue by siscia** [brocaar/loraserver#51]
Most likely is me missing something.

However the payload from the topic `application/[AppEUI]/node/[DevEUI]/rx` which is the one containing the data from the motes does not contains any reference to the time when the message has been sent.

How do I know when a particular messages is been sent?

**Comment by brocaar** [comment]
Yes you're right. I think it makes sense to add a `time` field to the rx payload containing the time when the payload was received by the gateway.

**Comment by siscia** [comment]
I can provide a PR Tomorrow hopefully ;)

**Comment by OpenSourceTycoon** [comment]
@brocaar ,

can i help you in RESTFul side ?

**Comment by brocaar** [comment]
I've merged your PR :-)
