### ISSUE TITLE
Deletion of node doesn't affect Redis DB

### ISSUE THREAD

**Issue by iBrick** [brocaar/loraserver#59]
Looks like there's a bug in Delete method for Node. 
When I press 'Delete' button the row is deleted from Postgres DB, but it stays in Redis DB.
So if you create a node with same DevEUI again all previous settings are back (but the data is not coming for the old settings and start coming only when you change DevAddr and keys).

**Comment by brocaar** [comment]
Thanks for reporting this! I'll look into later today.

**Comment by iBrick** [comment]
Thank you very much!
