### ISSUE TITLE
Which component is responsible for downlink duty-cycle management?

### ISSUE THREAD

**Issue by brocaar** [brocaar/loraserver#70]
For uplink, I think it is the responsibility of the node that it does not exceed its duty-cycle (e.g. for the EU ISM band). Which component should be responsible for downlink? Is this the network server, or is it the responsibility of the gateway (packet_forwarder)?

**Comment by nestorayuso** [comment]
Is the network server responsability, but up to date none of the network servers implement it.

ADR, Transmit-Power-Control, downlink gateway election, RX1 or RX2 election, channel planning and downlink duty-cycle are highly coupled and I think must by implemented by the same module.

**Comment by ivajloip** [comment]
I agree with @nestorayuso. In my mind, the gateway should return an error if the duty cycle will be exceeded (i.e. the network server is misbehaving), but I doubt that it's implemented.
