### ISSUE TITLE
How to send data to the end nodes?

### ISSUE THREAD

**Issue by glederer007** [brocaar/loraserver#72]
If it is possible, please include an example on how to send data (payload) to the end nodes. If I am not mistaken, currently there is no example for sending data only for receiving it. Thanks!

**Comment by brocaar** [comment]
Do you mean this? https://docs.loraserver.io/loraserver/sending-data/

**Comment by glederer007** [comment]
Unfortunately I have no experience with mosquitto. I understand what is needed to send packets to an end node, but what I miss is a sample mosquitto command like mosquitto_sub -t "application/0101010101010101/node/+/rx" -v you wrote for receiving packets.
