### ISSUE TITLE
Change DevAddr for an existing (ABP) Node Session

### ISSUE THREAD

**Issue by jamiechard** [brocaar/loraserver#76]
Hi. I want to manually change the DevAddr for an existing (ABP) Node Session. However, when I edit the existing ns (i.e. click on the Session / ABP button) and alter the DevAddr parameter (or alternatively click generate to do so) then I get the error "get node-session for DevAddr xxxxxxxx error: Redigo: nil returned" when I save changes. I assume this is because the new DevAddr is being used to search for the existing ns in Redis rather than the old DevAddr. Kind regards.

**Comment by brocaar** [comment]
Hi! This is a feature that isn't exposed in the web-interface (yet), but you can do this through the API. See `/api/v1` for all the API methods.
