### ISSUE TITLE
[UIX] Add option menu for application id in the new-node form.

### ISSUE THREAD

**Issue by siscia** [brocaar/loraserver#77]
When adding a new node it could be interesting to have an option menu for the application options.

In this way it will be simpler and faster to add nodes without making errors.

**Comment by brocaar** [comment]
I agree the ui could get some more love :-) Please note that for now, it is just a thin JS layer on top of the API just so you don't have to use REST client to get up and running. Making a better ui is on my backlog, but for now I'd like to focus on #68 and #55 and maybe #31. When #68 is in place, it means you can use whatever backend you wish for managing your inventory etc...
