### ISSUE TITLE
LoRaServer would send 'UnconfirmedDataDown'  when a 'UnconfirmedDataUp' was received.

### ISSUE THREAD

**Issue by john-bigz** [brocaar/loraserver#87]
I wonder if it would send 'UnconfirmedDataDown' when LoRaServer received a 'UnconfirmedDataUp'.
looking at the code below: ( [loraserver/internal/downlink/data.go)](https://github.com/brocaar/loraserver/blob/master/internal/downlink/data.go#L200)
```
// uplink was unconfirmed and no downlink data in queue and no mac commands to send
if txPayload == nil && rxPacket.PHYPayload.MHDR.MType == lorawan.UnconfirmedDataUp && len(macCommands) == 0 {
    return nil
}
```
the modified code as below:
```
// uplink was unconfirmed OR (no downlink data in queue and no mac commands to send)
if rxPacket.PHYPayload.MHDR.MType == lorawan.UnconfirmedDataUp || (txPayload == nil && len(macCommands) == 0) {
	    return nil
}```

**Comment by brocaar** [comment]
I think the current code is correct?

The reason is that an `UnconfirmedDataUp` doesn't need an `ACK`, thus when there is nothing to send back (`txPayload=nil` **and** `len(macCommands)=0`), we return. So all conditions must match.

When an `ConfirmedDataUp` is received, LoRa Server always needs to respond since it needs to `ACK` the received frame.

**Comment by ivajloip** [comment]
I also think that the current implementation is correct. Even if the message is unconfirmed, we might still want to reply if there is a pending dataDown packet (which is not possible with the suggested modification).

**Comment by john-bigz** [comment]
Yes, I made a mistake, the server still need to send pending data-down packets when it receives data-up packet, even if the data-up packet is an unconfirmedDataUp packet.

**Comment by brocaar** [comment]
No worries :-) Thanks for reviewing the code! If you find any other issues
or have any doubts or questions, please let me know.
