### ISSUE TITLE
Strip binaries for release

### ISSUE THREAD

**Issue by siscia** [brocaar/loraserver#89]
It seems to me (I could be wrong) that the binaries are not stripped when released.

Stripping comes with some tradeoff, but it is usually well worthed in the release.

The loraserver goes from 16MB to 9.2MB when stripped -> +40% reduction
Similarly the lora-app-server.

To strip the binaries is sufficient to add "-w -s" to the -ldflags.

**Comment by brocaar** [comment]
Hi @siscia I'll look into it to see if there is any negative impact. For now this hasn't been an issue as usually a few more megabytes isn't an issue, but if there is no impact, then I don't see a reason why we shouldn't strip the binaries :-)

**Comment by siscia** [comment]
:+1: I definitely agree that it is not a pressing issues.

**Comment by brocaar** [comment]
I think it is time to actually implement this :-) I never really took the time to dive into this, but after doing some research, I don't think that normal users should see any difference when compiling with `-w -s`. I think it only matters when using external tools for debugging, but in that case one could also compile a custom binary if needed.

https://stackoverflow.com/questions/22267189/what-does-the-w-flag-mean-when-passed-in-via-the-ldflags-option-to-the-go-comman
> None of these - not -ldflags -w, not -ldflags -s, not strip -s - should affect the execution of the actual program. They only affect whether you can debug or analyze the program with other tools.
