### ISSUE TITLE
DevEUI in capital letters

### ISSUE THREAD

**Issue by NICOLASGON** [brocaar/loraserver#90]
Hello,

When i do a moquitto_pub with the payload DevEUI and the topic DevEUI both in capital letters here is the error message : 

lora-app-server[22155]: time="2016-10-12T16:01:11+02:00" level=warning msg="handler/mqtt: topic DevEUI must match payload DevEUI" payload_dev_eui=396b7b2800000002 topic_dev_eui=396B7B2800000002

Is it a bug ?
Sincerely yours,

**Comment by brocaar** [comment]
Hi @NICOLASGON, this might be something to add to the documentation, as MQTT topics are case-sensitive and currently lowercase is being used everywhere.
