### ISSUE TITLE
How to decode Lorawan Payload?

### ISSUE THREAD

**Issue by dashracer** [brocaar/loraserver#94]
Hi @brocaar ,

How to decode node payload if we know all the keys?

Thanks.

**Comment by brocaar** [comment]
This is handled by https://github.com/brocaar/lora-app-server (see also https://docs.loraserver.io/lora-app-server/features/), which uses https://godoc.org/github.com/brocaar/lorawan#EncryptFRMPayload for decryption.

**Comment by JiapengLi** [comment]
@dashracer  if you just want to decode LoRaWAN frame for single node, could also refer this tool https://github.com/jiapengli/lorawan-parser
